# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IFeature")

model_instance <- IFeature$new()

test_that("attributes", {
  # tests for the property `attributes` (IAttributesTable)

  # uncomment below to test the property
  #expect_equal(model.instance$`attributes`, "EXPECTED_RESULT")
})

test_that("boundingBox", {
  # tests for the property `boundingBox` (Envelope)

  # uncomment below to test the property
  #expect_equal(model.instance$`boundingBox`, "EXPECTED_RESULT")
})

test_that("geometry", {
  # tests for the property `geometry` (Geometry)

  # uncomment below to test the property
  #expect_equal(model.instance$`geometry`, "EXPECTED_RESULT")
})
