# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SurveyDetailsDTO")

model_instance <- SurveyDetailsDTO$new()

test_that("result", {
  # tests for the property `result` (AnyType)
  # The list of responses in the survey

  # uncomment below to test the property
  #expect_equal(model.instance$`result`, "EXPECTED_RESULT")
})
