# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RpmeVariable")

model_instance <- RpmeVariable$new()

test_that("dimensionId", {
  # tests for the property `dimensionId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dimensionId`, "EXPECTED_RESULT")
})

test_that("dimensionName", {
  # tests for the property `dimensionName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dimensionName`, "EXPECTED_RESULT")
})

test_that("levelId", {
  # tests for the property `levelId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`levelId`, "EXPECTED_RESULT")
})

test_that("levelName", {
  # tests for the property `levelName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`levelName`, "EXPECTED_RESULT")
})

test_that("surveyModeId", {
  # tests for the property `surveyModeId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyModeId`, "EXPECTED_RESULT")
})

test_that("surveyModeName", {
  # tests for the property `surveyModeName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyModeName`, "EXPECTED_RESULT")
})

test_that("variableDescription", {
  # tests for the property `variableDescription` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`variableDescription`, "EXPECTED_RESULT")
})

test_that("variableId", {
  # tests for the property `variableId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`variableId`, "EXPECTED_RESULT")
})

test_that("variableName", {
  # tests for the property `variableName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`variableName`, "EXPECTED_RESULT")
})
