# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommodityUnitsApi")

api_instance <- CommodityUnitsApi$new()

test_that("CommodityUnitsConversionListGet", {
  # tests for CommodityUnitsConversionListGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Provides conversion factors to Kilogram or Litres for each convertible unit of measure.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()  Some non-standard units of measure might have different a conversion factor based on the country [Adm0Code]; Other non-standard units of measure might have a different conversion factor based on the commodity [CommodityID] being measured. Other cases will have null adm0code and CommodityID. No mandatory parameter.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (optional)
  # @param commodity_id integer The exact ID of a Commodity, as found in /Commodities/List (optional)
  # @param from_unit_id integer The exact ID of the original unit of measure of the price of a commodity, as found in /CommodityUnits/List (optional)
  # @param to_unit_id integer The exact ID of the converted unit of measure of the price of a commodity, as found in /CommodityUnits/List (optional)
  # @param page integer Page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [PagedCommodityListDTO]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CommodityUnitsListGet", {
  # tests for CommodityUnitsListGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Provides the detailed list of the unit of measure available in DataBridges platform
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code (optional)
  # @param commodity_unit_name character The name, even partial and case insensitive, of a commodity unit (optional)
  # @param commodity_unit_id integer The exact ID of a commodity unit (optional)
  # @param page integer page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [PagedCommodityListDTO]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
