# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CurrencyDTO")

model_instance <- CurrencyDTO$new()

test_that("createDate", {
  # tests for the property `createDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`createDate`, "EXPECTED_RESULT")
})

test_that("extendedName", {
  # tests for the property `extendedName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`extendedName`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)
  # The internal ID of the unit

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of the unit

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("updateDate", {
  # tests for the property `updateDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updateDate`, "EXPECTED_RESULT")
})
