# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PagedSurveyListDTO")

model_instance <- PagedSurveyListDTO$new()

test_that("items", {
  # tests for the property `items` (array[SurveyListDTO])
  # The list of surveys

  # uncomment below to test the property
  #expect_equal(model.instance$`items`, "EXPECTED_RESULT")
})

test_that("page", {
  # tests for the property `page` (integer)
  # The current page

  # uncomment below to test the property
  #expect_equal(model.instance$`page`, "EXPECTED_RESULT")
})

test_that("totalItems", {
  # tests for the property `totalItems` (integer)
  # The total number of items

  # uncomment below to test the property
  #expect_equal(model.instance$`totalItems`, "EXPECTED_RESULT")
})
