# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SurveyListDTO")

model_instance <- SurveyListDTO$new()

test_that("adm0Code", {
  # tests for the property `adm0Code` (integer)
  # The internal code of the country where the survey has taken place

  # uncomment below to test the property
  #expect_equal(model.instance$`adm0Code`, "EXPECTED_RESULT")
})

test_that("baseData", {
  # tests for the property `baseData` (character)
  # The link to the JSON data reshaped on the base XLSForm

  # uncomment below to test the property
  #expect_equal(model.instance$`baseData`, "EXPECTED_RESULT")
})

test_that("baseXlsFormName", {
  # tests for the property `baseXlsFormName` (character)
  # The name of the base XLSForm used to build the XLSForm

  # uncomment below to test the property
  #expect_equal(model.instance$`baseXlsFormName`, "EXPECTED_RESULT")
})

test_that("countryName", {
  # tests for the property `countryName` (character)
  # The name of the country where the survey has taken place

  # uncomment below to test the property
  #expect_equal(model.instance$`countryName`, "EXPECTED_RESULT")
})

test_that("iso3Alpha3", {
  # tests for the property `iso3Alpha3` (character)
  # The ISO3 alpha code of the country where the survey has taken place

  # uncomment below to test the property
  #expect_equal(model.instance$`iso3Alpha3`, "EXPECTED_RESULT")
})

test_that("originalCsvFile", {
  # tests for the property `originalCsvFile` (character)
  # The link to download the original CSV file

  # uncomment below to test the property
  #expect_equal(model.instance$`originalCsvFile`, "EXPECTED_RESULT")
})

test_that("surveyCreateDate", {
  # tests for the property `surveyCreateDate` (character)
  # The date when the survey has been uploaded in the Data Bridges platform

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyCreateDate`, "EXPECTED_RESULT")
})

test_that("surveyEndDate", {
  # tests for the property `surveyEndDate` (character)
  # The date when the survey has ended

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyEndDate`, "EXPECTED_RESULT")
})

test_that("surveyID", {
  # tests for the property `surveyID` (integer)
  # The Id of the Survey

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyID`, "EXPECTED_RESULT")
})

test_that("surveyOriginalFilename", {
  # tests for the property `surveyOriginalFilename` (character)
  # The filename of the survey CSV file

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyOriginalFilename`, "EXPECTED_RESULT")
})

test_that("surveyStartDate", {
  # tests for the property `surveyStartDate` (character)
  # The date when the survey has started

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyStartDate`, "EXPECTED_RESULT")
})

test_that("surveyStatusID", {
  # tests for the property `surveyStatusID` (integer)
  # The Id of the Survey status

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyStatusID`, "EXPECTED_RESULT")
})

test_that("surveyValidationReport", {
  # tests for the property `surveyValidationReport` (character)
  # The detailed report on the validation performed on the survey schema

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyValidationReport`, "EXPECTED_RESULT")
})

test_that("userName", {
  # tests for the property `userName` (character)
  # The name of the user that has uploaded the survey data

  # uncomment below to test the property
  #expect_equal(model.instance$`userName`, "EXPECTED_RESULT")
})

test_that("xlsFormName", {
  # tests for the property `xlsFormName` (character)
  # The name of the XLSForm used to collect data

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormName`, "EXPECTED_RESULT")
})
