# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RpmeAssessment")

model_instance <- RpmeAssessment$new()

test_that("adm0Code", {
  # tests for the property `adm0Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm0Code`, "EXPECTED_RESULT")
})

test_that("adm0CodeDOTS", {
  # tests for the property `adm0CodeDOTS` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm0CodeDOTS`, "EXPECTED_RESULT")
})

test_that("adm1Code", {
  # tests for the property `adm1Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm1Code`, "EXPECTED_RESULT")
})

test_that("adm1CodeDOTS", {
  # tests for the property `adm1CodeDOTS` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm1CodeDOTS`, "EXPECTED_RESULT")
})

test_that("adm2Code", {
  # tests for the property `adm2Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm2Code`, "EXPECTED_RESULT")
})

test_that("adm2CodeDOTS", {
  # tests for the property `adm2CodeDOTS` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm2CodeDOTS`, "EXPECTED_RESULT")
})

test_that("assessmentDate", {
  # tests for the property `assessmentDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assessmentDate`, "EXPECTED_RESULT")
})

test_that("benSevCntrDev", {
  # tests for the property `benSevCntrDev` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`benSevCntrDev`, "EXPECTED_RESULT")
})

test_that("beneficiariesScoreTbu", {
  # tests for the property `beneficiariesScoreTbu` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`beneficiariesScoreTbu`, "EXPECTED_RESULT")
})

test_that("marketId", {
  # tests for the property `marketId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`marketId`, "EXPECTED_RESULT")
})

test_that("nbBeneficiariesInterviewed", {
  # tests for the property `nbBeneficiariesInterviewed` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nbBeneficiariesInterviewed`, "EXPECTED_RESULT")
})

test_that("outputValues", {
  # tests for the property `outputValues` (array[RpmeOutputValues])

  # uncomment below to test the property
  #expect_equal(model.instance$`outputValues`, "EXPECTED_RESULT")
})

test_that("priceScoreTbd", {
  # tests for the property `priceScoreTbd` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`priceScoreTbd`, "EXPECTED_RESULT")
})

test_that("priceScoreTbu", {
  # tests for the property `priceScoreTbu` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`priceScoreTbu`, "EXPECTED_RESULT")
})

test_that("sevCntrDev", {
  # tests for the property `sevCntrDev` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sevCntrDev`, "EXPECTED_RESULT")
})

test_that("shLatitude", {
  # tests for the property `shLatitude` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`shLatitude`, "EXPECTED_RESULT")
})

test_that("shLongitude", {
  # tests for the property `shLongitude` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`shLongitude`, "EXPECTED_RESULT")
})

test_that("shopId", {
  # tests for the property `shopId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`shopId`, "EXPECTED_RESULT")
})

test_that("surveyId", {
  # tests for the property `surveyId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyId`, "EXPECTED_RESULT")
})

test_that("trdName", {
  # tests for the property `trdName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`trdName`, "EXPECTED_RESULT")
})
