# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsdIndirectQuotation")

model_instance <- UsdIndirectQuotation$new()

test_that("adm0Code", {
  # tests for the property `adm0Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm0Code`, "EXPECTED_RESULT")
})

test_that("countryISO3", {
  # tests for the property `countryISO3` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`countryISO3`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

test_that("frequency", {
  # tests for the property `frequency` (character)
  # (it’s from the reporting commodity named Exchange Rate

  # uncomment below to test the property
  #expect_equal(model.instance$`frequency`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("isOfficial", {
  # tests for the property `isOfficial` (character)
  # The field IsOfficial is a boolean which can be set to true for the Trading Economics data and to false for the data coming from a commodity saved in the DataBridges database

  # uncomment below to test the property
  #expect_equal(model.instance$`isOfficial`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # the ISO3 code for the currency, based on ISO4217

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})
