# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NtsGeometryServices")

model_instance <- NtsGeometryServices$new()

test_that("coordinateEqualityComparer", {
  # tests for the property `coordinateEqualityComparer` (map(AnyType))

  # uncomment below to test the property
  #expect_equal(model.instance$`coordinateEqualityComparer`, "EXPECTED_RESULT")
})

test_that("defaultCoordinateSequenceFactory", {
  # tests for the property `defaultCoordinateSequenceFactory` (CoordinateSequenceFactory)

  # uncomment below to test the property
  #expect_equal(model.instance$`defaultCoordinateSequenceFactory`, "EXPECTED_RESULT")
})

test_that("defaultPrecisionModel", {
  # tests for the property `defaultPrecisionModel` (PrecisionModel)

  # uncomment below to test the property
  #expect_equal(model.instance$`defaultPrecisionModel`, "EXPECTED_RESULT")
})

test_that("defaultSRID", {
  # tests for the property `defaultSRID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`defaultSRID`, "EXPECTED_RESULT")
})

test_that("geometryOverlay", {
  # tests for the property `geometryOverlay` (map(AnyType))

  # uncomment below to test the property
  #expect_equal(model.instance$`geometryOverlay`, "EXPECTED_RESULT")
})
