# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Envelope")

model_instance <- Envelope$new()

test_that("area", {
  # tests for the property `area` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`area`, "EXPECTED_RESULT")
})

test_that("centre", {
  # tests for the property `centre` (Coordinate)

  # uncomment below to test the property
  #expect_equal(model.instance$`centre`, "EXPECTED_RESULT")
})

test_that("diameter", {
  # tests for the property `diameter` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`diameter`, "EXPECTED_RESULT")
})

test_that("height", {
  # tests for the property `height` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`height`, "EXPECTED_RESULT")
})

test_that("isNull", {
  # tests for the property `isNull` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isNull`, "EXPECTED_RESULT")
})

test_that("maxExtent", {
  # tests for the property `maxExtent` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxExtent`, "EXPECTED_RESULT")
})

test_that("maxX", {
  # tests for the property `maxX` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxX`, "EXPECTED_RESULT")
})

test_that("maxY", {
  # tests for the property `maxY` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxY`, "EXPECTED_RESULT")
})

test_that("minExtent", {
  # tests for the property `minExtent` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`minExtent`, "EXPECTED_RESULT")
})

test_that("minX", {
  # tests for the property `minX` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`minX`, "EXPECTED_RESULT")
})

test_that("minY", {
  # tests for the property `minY` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`minY`, "EXPECTED_RESULT")
})

test_that("width", {
  # tests for the property `width` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`width`, "EXPECTED_RESULT")
})
