# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RpmeOutputValues")

model_instance <- RpmeOutputValues$new()

test_that("outputValue", {
  # tests for the property `outputValue` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`outputValue`, "EXPECTED_RESULT")
})

test_that("variableId", {
  # tests for the property `variableId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`variableId`, "EXPECTED_RESULT")
})
