# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GeometryFactory")

model_instance <- GeometryFactory$new()

test_that("coordinateSequenceFactory", {
  # tests for the property `coordinateSequenceFactory` (CoordinateSequenceFactory)

  # uncomment below to test the property
  #expect_equal(model.instance$`coordinateSequenceFactory`, "EXPECTED_RESULT")
})

test_that("geometryServices", {
  # tests for the property `geometryServices` (NtsGeometryServices)

  # uncomment below to test the property
  #expect_equal(model.instance$`geometryServices`, "EXPECTED_RESULT")
})

test_that("precisionModel", {
  # tests for the property `precisionModel` (PrecisionModel)

  # uncomment below to test the property
  #expect_equal(model.instance$`precisionModel`, "EXPECTED_RESULT")
})

test_that("srid", {
  # tests for the property `srid` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`srid`, "EXPECTED_RESULT")
})
