# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test XlsFormDefinitionDTO")

model_instance <- XlsFormDefinitionDTO$new()

test_that("xlsFormFieldLabel", {
  # tests for the property `xlsFormFieldLabel` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormFieldLabel`, "EXPECTED_RESULT")
})

test_that("xlsFormFieldName", {
  # tests for the property `xlsFormFieldName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormFieldName`, "EXPECTED_RESULT")
})

test_that("xlsFormFieldRow", {
  # tests for the property `xlsFormFieldRow` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormFieldRow`, "EXPECTED_RESULT")
})

test_that("xlsFormFieldType", {
  # tests for the property `xlsFormFieldType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormFieldType`, "EXPECTED_RESULT")
})

test_that("xlsFormListId", {
  # tests for the property `xlsFormListId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormListId`, "EXPECTED_RESULT")
})
