# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Coordinate")

model_instance <- Coordinate$new()

test_that("coordinateValue", {
  # tests for the property `coordinateValue` (Coordinate)

  # uncomment below to test the property
  #expect_equal(model.instance$`coordinateValue`, "EXPECTED_RESULT")
})

test_that("m", {
  # tests for the property `m` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`m`, "EXPECTED_RESULT")
})

test_that("x", {
  # tests for the property `x` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`x`, "EXPECTED_RESULT")
})

test_that("y", {
  # tests for the property `y` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`y`, "EXPECTED_RESULT")
})

test_that("z", {
  # tests for the property `z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`z`, "EXPECTED_RESULT")
})
