# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CoordinateSequenceFactory")

model_instance <- CoordinateSequenceFactory$new()

test_that("ordinates", {
  # tests for the property `ordinates` (Ordinates)

  # uncomment below to test the property
  #expect_equal(model.instance$`ordinates`, "EXPECTED_RESULT")
})
