# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IpcValue")

model_instance <- IpcValue$new()

test_that("ipcAnalysedPercentage", {
  # tests for the property `ipcAnalysedPercentage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcAnalysedPercentage`, "EXPECTED_RESULT")
})

test_that("ipcAnalysedPopulation", {
  # tests for the property `ipcAnalysedPopulation` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcAnalysedPopulation`, "EXPECTED_RESULT")
})

test_that("ipcAnalysisComment", {
  # tests for the property `ipcAnalysisComment` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcAnalysisComment`, "EXPECTED_RESULT")
})

test_that("ipcAreaName", {
  # tests for the property `ipcAreaName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcAreaName`, "EXPECTED_RESULT")
})

test_that("ipcCountryName", {
  # tests for the property `ipcCountryName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcCountryName`, "EXPECTED_RESULT")
})

test_that("ipcCreateDate", {
  # tests for the property `ipcCreateDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcCreateDate`, "EXPECTED_RESULT")
})

test_that("ipcDataSource", {
  # tests for the property `ipcDataSource` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcDataSource`, "EXPECTED_RESULT")
})

test_that("ipcDataType", {
  # tests for the property `ipcDataType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcDataType`, "EXPECTED_RESULT")
})

test_that("ipcId", {
  # tests for the property `ipcId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcId`, "EXPECTED_RESULT")
})

test_that("ipcIsLatestValue", {
  # tests for the property `ipcIsLatestValue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcIsLatestValue`, "EXPECTED_RESULT")
})

test_that("ipcPhase3Percentage", {
  # tests for the property `ipcPhase3Percentage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcPhase3Percentage`, "EXPECTED_RESULT")
})

test_that("ipcPhase3Population", {
  # tests for the property `ipcPhase3Population` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcPhase3Population`, "EXPECTED_RESULT")
})

test_that("ipcPhase4Percentage", {
  # tests for the property `ipcPhase4Percentage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcPhase4Percentage`, "EXPECTED_RESULT")
})

test_that("ipcPhase4Population", {
  # tests for the property `ipcPhase4Population` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcPhase4Population`, "EXPECTED_RESULT")
})

test_that("ipcPhase5Percentage", {
  # tests for the property `ipcPhase5Percentage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcPhase5Percentage`, "EXPECTED_RESULT")
})

test_that("ipcPhase5Population", {
  # tests for the property `ipcPhase5Population` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcPhase5Population`, "EXPECTED_RESULT")
})

test_that("ipcReferencePeriod", {
  # tests for the property `ipcReferencePeriod` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcReferencePeriod`, "EXPECTED_RESULT")
})

test_that("ipcUpdateDate", {
  # tests for the property `ipcUpdateDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcUpdateDate`, "EXPECTED_RESULT")
})

test_that("ipcYear", {
  # tests for the property `ipcYear` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipcYear`, "EXPECTED_RESULT")
})

test_that("iso3Alpha3", {
  # tests for the property `iso3Alpha3` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`iso3Alpha3`, "EXPECTED_RESULT")
})
