# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommodityDTO")

model_instance <- CommodityDTO$new()

test_that("categoryId", {
  # tests for the property `categoryId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`categoryId`, "EXPECTED_RESULT")
})

test_that("coicop2018", {
  # tests for the property `coicop2018` (character)
  # The COICOP 2018 definition

  # uncomment below to test the property
  #expect_equal(model.instance$`coicop2018`, "EXPECTED_RESULT")
})

test_that("createDate", {
  # tests for the property `createDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`createDate`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)
  # The internal ID of the commodity

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of the commodity

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("parentId", {
  # tests for the property `parentId` (integer)
  # The internal parent ID of the commodity

  # uncomment below to test the property
  #expect_equal(model.instance$`parentId`, "EXPECTED_RESULT")
})

test_that("processing", {
  # tests for the property `processing` (array[CommodityProcessingDTO])

  # uncomment below to test the property
  #expect_equal(model.instance$`processing`, "EXPECTED_RESULT")
})

test_that("qualities", {
  # tests for the property `qualities` (array[CommodityQualityDTO])

  # uncomment below to test the property
  #expect_equal(model.instance$`qualities`, "EXPECTED_RESULT")
})

test_that("supply", {
  # tests for the property `supply` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`supply`, "EXPECTED_RESULT")
})

test_that("updateDate", {
  # tests for the property `updateDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updateDate`, "EXPECTED_RESULT")
})
