# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MarketPricesApi")

api_instance <- MarketPricesApi$new()

test_that("MarketPricesAlpsGet", {
  # tests for MarketPricesAlpsGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Returns time series values of ALPS and PEWI.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()  Returns the full time series of the Alert for Price Spikes (ALPS) and the value of the Price Early Warning Index (PEWI). Methodology is available in [DataViz](https://dataviz.vam.wfp.org/) and [VAM-Resource Centre](https://resources.vam.wfp.org/). Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (optional)
  # @param market_id integer Unique ID of a Market, as found in /Markets/GeoJSONList (optional)
  # @param commodity_id integer The exact ID of a Commodity, as found in /Commodities/List (optional)
  # @param price_type_name character Price type: [retail|wholesale|farmgate] (optional)
  # @param currency_id integer The exact ID of a currency, as found in /Currency/List (optional)
  # @param price_flag character Type of price data: [actual|aggregate|estimated|forecasted] (optional)
  # @param start_date character Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param end_date character Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param latest_value_only character [TRUE|FALSE] (optional)
  # @param page integer Page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [ViewExtendedAlpsValuePagedResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketPricesPriceDailyGet", {
  # tests for MarketPricesPriceDailyGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Returns a daily time series of commodity market prices.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()  This is the highest frequency available. Data is flagged according to its pre-processing characteristics. Actual data is collected originally with daily frequency; aggregated data returns an empty list; imputed data is an estimation of missing values in the time series, obtained through the R Amelia-II package;        forecasted data is a six months prediction obtained through different methods, which are reported in the API.  For country specific meta-data please refer to documentation available in DataLibrary. For specific methodological notes on forecasts and imputations refer to the dedicated page in DataViz.  Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (optional)
  # @param market_id integer Unique ID of a Market, as found in /Markets/GeoJSONList (optional)
  # @param commodity_id integer The exact ID of a Commodity, as found in /Commodities/List (optional)
  # @param price_type_name character Price type: [retail|wholesale|farmgate] (optional)
  # @param currency_id integer The exact ID of a currency, as found in /Currency/List (optional)
  # @param price_flag character Type of price data: [actual|aggregate|estimated|forecasted] (optional)
  # @param start_date character Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param end_date character Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param latest_value_only character [TRUE|FALSE] (optional)
  # @param page integer Page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [ViewExtendedAggregatedPricePagedResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketPricesPriceMonthlyGet", {
  # tests for MarketPricesPriceMonthlyGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Returns a monthly time series of commodity market prices.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()  This is the lowest frequency available and the most complete data source. Data is flagged according to its pre-processing characteristics. actual data is collected originally with monthly frequency; aggregated data is collected with higher frequency (daily or weekly) averaged through a weighted mean to monthly; imputed data is an estimation of missing values in the time series, obtained through the R Amelia-II package; forecasted data is a six months prediction obtained through different methods, which are reported in the API. For country specific meta-data please refer to documentation available in [DataLibrary](https://datalib.vam.wfp.org/). For specific methodological notes on forecasts and imputations refer to the dedicated page in [DataViz](https://dataviz.vam.wfp.org/). Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (optional)
  # @param market_id integer Unique ID of a Market, as found in /Markets/GeoJSONList (optional)
  # @param commodity_id integer The exact ID of a Commodity, as found in /Commodities/List (optional)
  # @param price_type_name character Price type: [retail|wholesale|farmgate] (optional)
  # @param currency_id integer The exact ID of a currency, as found in /Currency/List (optional)
  # @param price_flag character Type of price data: [actual|aggregate|estimated|forecasted] (optional)
  # @param start_date character Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param end_date character Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param latest_value_only character [TRUE|FALSE] (optional)
  # @param page integer Page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [ViewExtendedAggregatedPricePagedResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketPricesPriceRawGet", {
  # tests for MarketPricesPriceRawGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Returns original commodity market prices
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Restricted-yellow)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Official%20Use%20Only-yellow)]()  ### This endpoint is restricted, it requires the scope: \&quot;vamdatabridges_marketprices-priceraw_get\&quot;  Restricted endpoint. Returns the original data with the entire Commodity Price Metadata as inserted by the focal point, which might contain sensitive or personal informatio. Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (optional)
  # @param market_id integer Unique ID of a Market, as found in /Markets/GeoJSONList (optional)
  # @param commodity_id integer The exact ID of a Commodity, as found in /Commodities/List (optional)
  # @param price_type_name character Price type: [retail|wholesale|farmgate] (optional)
  # @param currency_id integer The exact ID of a currency, as found in /Currency/List (optional)
  # @param price_flag character Type of price data: [actual|aggregate|estimated|forecasted] (optional)
  # @param start_date character Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param end_date character Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param latest_value_only character [TRUE|FALSE] (optional)
  # @param page integer Page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [PagedCommodityPriceListDTO]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketPricesPriceWeeklyGet", {
  # tests for MarketPricesPriceWeeklyGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Returns a weekly time series of commodity market prices.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()  Weeks used as reference are the International Organization for Standardization (ISO) week-numbering year (ISO-8601). Data is flagged according to its pre-processing characteristics. Aactual data is collected originally with weekly frequency; aggregated data is collected with higher frequency (daily) averaged through a weighted mean to weekly; imputed data is an estimation of missing values in the time series, obtained through the R Amelia-II package; forecasted data is a six months prediction obtained through different methods, which are reported in the API. For country specific meta-data please refer to documentation available in [DataLibrary](https://datalib.vam.wfp.org/). For specific methodological notes on forecasts and imputations refer to the dedicated page in [DataViz](https://dataviz.vam.wfp.org/). Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (optional)
  # @param market_id integer Unique ID of a Market, as found in /Markets/GeoJSONList (optional)
  # @param commodity_id integer The exact ID of a Commodity, as found in /Commodities/List (optional)
  # @param price_type_name character Price type: [retail|wholesale|farmgate] (optional)
  # @param currency_id integer The exact ID of a currency, as found in /Currency/List (optional)
  # @param price_flag character Type of price data: [actual|aggregate|estimated|forecasted] (optional)
  # @param start_date character Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param end_date character Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (optional)
  # @param latest_value_only character [TRUE|FALSE] (optional)
  # @param page integer Page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [PagedCommodityWeeklyAggregatedPriceListDTO]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
