# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test XlsFormDTO")

model_instance <- XlsFormDTO$new()

test_that("adm0Code", {
  # tests for the property `adm0Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm0Code`, "EXPECTED_RESULT")
})

test_that("userName", {
  # tests for the property `userName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userName`, "EXPECTED_RESULT")
})

test_that("xlsFormCreateDate", {
  # tests for the property `xlsFormCreateDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormCreateDate`, "EXPECTED_RESULT")
})

test_that("xlsFormID", {
  # tests for the property `xlsFormID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormID`, "EXPECTED_RESULT")
})

test_that("xlsFormIsBaseSchema", {
  # tests for the property `xlsFormIsBaseSchema` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormIsBaseSchema`, "EXPECTED_RESULT")
})

test_that("xlsFormName", {
  # tests for the property `xlsFormName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormName`, "EXPECTED_RESULT")
})

test_that("xlsFormSourceFile", {
  # tests for the property `xlsFormSourceFile` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`xlsFormSourceFile`, "EXPECTED_RESULT")
})
