# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MarketsApi")

api_instance <- MarketsApi$new()

test_that("MarketsGeoJSONListGet", {
  # tests for MarketsGeoJSONListGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Provide a list of geo referenced markets in a specific country
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param adm0code integer The admin code of the country (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [array[IFeature]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketsListGet", {
  # tests for MarketsListGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Get a complete list of markets in a country
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code (optional)
  # @param page integer page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketsMarketsAsCSVGet", {
  # tests for MarketsMarketsAsCSVGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Get a complete list of markets in a country
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param adm0code integer The admin code of the country (optional)
  # @param local_names character If true the name of markets and regions will be localized if available (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MarketsNearbyMarketsGet", {
  # tests for MarketsNearbyMarketsGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Find markets near a given location by longitude and latitude within a 15Km distance
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param adm0code integer code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion (optional)
  # @param lat numeric latitude of the point that will be used to search for existing nearby markets. Geo-reference standard used for this coordinate is decimal (optional)
  # @param lng numeric longitude of the point that will be used to search for existing nearby markets.  Geo-reference standard used for this coordinate is decimal (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [array[NearbyMarketsDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
