# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PrecisionModel")

model_instance <- PrecisionModel$new()

test_that("isFloating", {
  # tests for the property `isFloating` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isFloating`, "EXPECTED_RESULT")
})

test_that("maximumSignificantDigits", {
  # tests for the property `maximumSignificantDigits` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`maximumSignificantDigits`, "EXPECTED_RESULT")
})

test_that("precisionModelType", {
  # tests for the property `precisionModelType` (PrecisionModels)

  # uncomment below to test the property
  #expect_equal(model.instance$`precisionModelType`, "EXPECTED_RESULT")
})

test_that("scale", {
  # tests for the property `scale` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`scale`, "EXPECTED_RESULT")
})
