# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommoditiesApi")

api_instance <- CommoditiesApi$new()

test_that("CommoditiesCategoriesListGet", {
  # tests for CommoditiesCategoriesListGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Provides the list of categories.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()  Categories are matched with high level WFP commodity classification at level 1. No mandatory parameter.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code (optional)
  # @param category_name character The name, even partial and case insensitive, of a commodity category. (optional)
  # @param category_id integer The exact ID of a Commodity, as found in /Commodities/List. (optional)
  # @param page integer page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [PagedCommodityListDTO]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CommoditiesListGet", {
  # tests for CommoditiesListGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Provide the detailed list of the commodities available in DataBridges platform
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()  COICOP 2018 codes are returned to hierarchically matching categories based on [UN-Statistical Division codes](https://unstats.un.org/unsd/classifications/Econ/). No mandatory parameter.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code (optional)
  # @param commodity_name character The name, even partial and case insensitive, of a commodity (optional)
  # @param commodity_id integer The exact ID of a commodity (optional)
  # @param page integer page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [PagedCommodityListDTO]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
