# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EconomicIndicatorProperty")

model_instance <- EconomicIndicatorProperty$new()

test_that("countryIso3", {
  # tests for the property `countryIso3` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`countryIso3`, "EXPECTED_RESULT")
})

test_that("dataSource", {
  # tests for the property `dataSource` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dataSource`, "EXPECTED_RESULT")
})

test_that("frequency", {
  # tests for the property `frequency` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`frequency`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("latestValue", {
  # tests for the property `latestValue` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`latestValue`, "EXPECTED_RESULT")
})

test_that("latestValueDate", {
  # tests for the property `latestValueDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`latestValueDate`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("unit", {
  # tests for the property `unit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`unit`, "EXPECTED_RESULT")
})
