# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CurrencyApi")

api_instance <- CurrencyApi$new()

test_that("CurrencyListGet", {
  # tests for CurrencyListGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Returns the list of currencies available in the internal VAM database, with Currency 3-letter code, matching with ISO 4217.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_code character The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (optional)
  # @param currency_name character Currency 3-letter code, matching with ISO 4217. (optional)
  # @param currency_id integer Unique code to identify the currency in internal VAM currencies. (optional)
  # @param page integer Page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [PagedCurrencyListDTO]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CurrencyUsdIndirectQuotationGet", {
  # tests for CurrencyUsdIndirectQuotationGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Returns the value of the Exchange rates from Trading Economics, for official rates, and DataViz for unofficial rates.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()  Returns the time series of values of the Exchange rate of the Local Currency for buying 1 USD in the official market. Original frequency for official rates is daily, non-indicated. Unofficial rates are aggregated at national level by the original frequency of collection. For greater detail on unofficial exchange rates, explore the Exchange Rate (unofficial) commodity in Market Prices Prices. No mandatory parameter.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param country_iso3 character The code to identify the country. Must be a ISO-3166 Alpha 3 code. (optional)
  # @param currency_name character the ISO3 code for the currency, based on ISO4217 (optional)
  # @param page integer Page number for paged results (optional)
  # @param format character Output format: [JSON|CSV] Json is the default value (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [UsdIndirectQuotationPagedResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
