# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GorpValueWithChanges")

model_instance <- GorpValueWithChanges$new()

test_that("absoluteChange", {
  # tests for the property `absoluteChange` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`absoluteChange`, "EXPECTED_RESULT")
})

test_that("actualValue", {
  # tests for the property `actualValue` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`actualValue`, "EXPECTED_RESULT")
})

test_that("baselineValue", {
  # tests for the property `baselineValue` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`baselineValue`, "EXPECTED_RESULT")
})

test_that("comments", {
  # tests for the property `comments` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`comments`, "EXPECTED_RESULT")
})

test_that("month", {
  # tests for the property `month` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`month`, "EXPECTED_RESULT")
})

test_that("numberOfCountries", {
  # tests for the property `numberOfCountries` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numberOfCountries`, "EXPECTED_RESULT")
})

test_that("percentageChange", {
  # tests for the property `percentageChange` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`percentageChange`, "EXPECTED_RESULT")
})

test_that("regionName", {
  # tests for the property `regionName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`regionName`, "EXPECTED_RESULT")
})

test_that("year", {
  # tests for the property `year` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`year`, "EXPECTED_RESULT")
})
