# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GorpApi")

api_instance <- GorpApi$new()

test_that("GorpLatestGet", {
  # tests for GorpLatestGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Return the latest dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param page integer  (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [GorpValueWithChangesPagedResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GorpListGet", {
  # tests for GorpListGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Return the full dataset of number of acutely food insecure (in millions) based on WFP Global Operational Response Plan.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param page integer  (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [GorpValueWithChangesPagedResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
