# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NearbyMarketsDTO")

model_instance <- NearbyMarketsDTO$new()

test_that("distance", {
  # tests for the property `distance` (numeric)
  # The distance in meters of the market from the provided point

  # uncomment below to test the property
  #expect_equal(model.instance$`distance`, "EXPECTED_RESULT")
})

test_that("marketId", {
  # tests for the property `marketId` (integer)
  # The internal ID of the market

  # uncomment below to test the property
  #expect_equal(model.instance$`marketId`, "EXPECTED_RESULT")
})

test_that("marketName", {
  # tests for the property `marketName` (character)
  # The name of the market

  # uncomment below to test the property
  #expect_equal(model.instance$`marketName`, "EXPECTED_RESULT")
})
