# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RpmeApi")

api_instance <- RpmeApi$new()

test_that("RpmeOutputValuesGet", {
  # tests for RpmeOutputValuesGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Processed values for each variable used in the assessments
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param page integer page number for paged results (optional)
  # @param adm0_code integer Code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion (optional)
  # @param survey_id integer The ID of the survey (optional)
  # @param shop_id integer The ID of the shop (optional)
  # @param market_id integer The ID of the market (optional)
  # @param adm0_code_dots character  (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [RpmeAssessmentPagedResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RpmeSurveysGet", {
  # tests for RpmeSurveysGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all RPME surveys conducted in a country. The date of reference, SurveyDate, for the data collection is set by the officer responsible for the upload of each survey.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param adm0_code integer code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion (optional)
  # @param page integer page number for paged results (optional)
  # @param start_date character starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24) (optional)
  # @param end_date character ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24) (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [array[PagedSurveyListDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RpmeVariablesGet", {
  # tests for RpmeVariablesGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # List of variables
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param page integer  (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [RpmeVariablePagedResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RpmeXLSFormsGet", {
  # tests for RpmeXLSFormsGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  # Get a complete list of XLS Forms uploaded on the RPME in a given period of data collection. This is the digital version of the questionnaire used during the data collection exercise.
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param adm0_code integer code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion (optional)
  # @param page integer page number for paged results (optional)
  # @param start_date character starting date for the range in which data using this XLSForm was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24) (optional)
  # @param end_date character ending date for the range in which data using this XLSForm was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24) (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [array[PagedXlsFormListDTO]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
