# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MFIProcessedDataDTO")

model_instance <- MFIProcessedDataDTO$new()

test_that("adm0Code", {
  # tests for the property `adm0Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm0Code`, "EXPECTED_RESULT")
})

test_that("adm0Name", {
  # tests for the property `adm0Name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm0Name`, "EXPECTED_RESULT")
})

test_that("adm1Code", {
  # tests for the property `adm1Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm1Code`, "EXPECTED_RESULT")
})

test_that("adm1Name", {
  # tests for the property `adm1Name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm1Name`, "EXPECTED_RESULT")
})

test_that("adm2Code", {
  # tests for the property `adm2Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm2Code`, "EXPECTED_RESULT")
})

test_that("adm2Name", {
  # tests for the property `adm2Name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm2Name`, "EXPECTED_RESULT")
})

test_that("baseXlsFormID", {
  # tests for the property `baseXlsFormID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`baseXlsFormID`, "EXPECTED_RESULT")
})

test_that("baseXlsFormName", {
  # tests for the property `baseXlsFormName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`baseXlsFormName`, "EXPECTED_RESULT")
})

test_that("dimensionID", {
  # tests for the property `dimensionID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dimensionID`, "EXPECTED_RESULT")
})

test_that("dimensionName", {
  # tests for the property `dimensionName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dimensionName`, "EXPECTED_RESULT")
})

test_that("endDate", {
  # tests for the property `endDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`endDate`, "EXPECTED_RESULT")
})

test_that("levelID", {
  # tests for the property `levelID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`levelID`, "EXPECTED_RESULT")
})

test_that("levelName", {
  # tests for the property `levelName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`levelName`, "EXPECTED_RESULT")
})

test_that("marketID", {
  # tests for the property `marketID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`marketID`, "EXPECTED_RESULT")
})

test_that("marketLatitude", {
  # tests for the property `marketLatitude` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`marketLatitude`, "EXPECTED_RESULT")
})

test_that("marketLongitude", {
  # tests for the property `marketLongitude` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`marketLongitude`, "EXPECTED_RESULT")
})

test_that("marketName", {
  # tests for the property `marketName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`marketName`, "EXPECTED_RESULT")
})

test_that("outputValue", {
  # tests for the property `outputValue` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`outputValue`, "EXPECTED_RESULT")
})

test_that("regionalBureauID", {
  # tests for the property `regionalBureauID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`regionalBureauID`, "EXPECTED_RESULT")
})

test_that("regionalBureauName", {
  # tests for the property `regionalBureauName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`regionalBureauName`, "EXPECTED_RESULT")
})

test_that("startDate", {
  # tests for the property `startDate` (character)
  # The Id of the Survey status

  # uncomment below to test the property
  #expect_equal(model.instance$`startDate`, "EXPECTED_RESULT")
})

test_that("surveyID", {
  # tests for the property `surveyID` (integer)
  # The Id of the Survey

  # uncomment below to test the property
  #expect_equal(model.instance$`surveyID`, "EXPECTED_RESULT")
})

test_that("tradersSampleSize", {
  # tests for the property `tradersSampleSize` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`tradersSampleSize`, "EXPECTED_RESULT")
})

test_that("variableID", {
  # tests for the property `variableID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`variableID`, "EXPECTED_RESULT")
})

test_that("variableLabel", {
  # tests for the property `variableLabel` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`variableLabel`, "EXPECTED_RESULT")
})

test_that("variableName", {
  # tests for the property `variableName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`variableName`, "EXPECTED_RESULT")
})
