# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CoordinateSequence")

model_instance <- CoordinateSequence$new()

test_that("count", {
  # tests for the property `count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})

test_that("dimension", {
  # tests for the property `dimension` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dimension`, "EXPECTED_RESULT")
})

test_that("hasM", {
  # tests for the property `hasM` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hasM`, "EXPECTED_RESULT")
})

test_that("hasZ", {
  # tests for the property `hasZ` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hasZ`, "EXPECTED_RESULT")
})

test_that("mOrdinateIndex", {
  # tests for the property `mOrdinateIndex` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`mOrdinateIndex`, "EXPECTED_RESULT")
})

test_that("measures", {
  # tests for the property `measures` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`measures`, "EXPECTED_RESULT")
})

test_that("ordinates", {
  # tests for the property `ordinates` (Ordinates)

  # uncomment below to test the property
  #expect_equal(model.instance$`ordinates`, "EXPECTED_RESULT")
})

test_that("spatial", {
  # tests for the property `spatial` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`spatial`, "EXPECTED_RESULT")
})

test_that("zOrdinateIndex", {
  # tests for the property `zOrdinateIndex` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`zOrdinateIndex`, "EXPECTED_RESULT")
})
