# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ViewExtendedAlpsValue")

model_instance <- ViewExtendedAlpsValue$new()

test_that("adm0Code", {
  # tests for the property `adm0Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm0Code`, "EXPECTED_RESULT")
})

test_that("analysisValueEstimatedPrice", {
  # tests for the property `analysisValueEstimatedPrice` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`analysisValueEstimatedPrice`, "EXPECTED_RESULT")
})

test_that("analysisValuePewiValue", {
  # tests for the property `analysisValuePewiValue` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`analysisValuePewiValue`, "EXPECTED_RESULT")
})

test_that("analysisValuePriceFlag", {
  # tests for the property `analysisValuePriceFlag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`analysisValuePriceFlag`, "EXPECTED_RESULT")
})

test_that("commodityID", {
  # tests for the property `commodityID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityID`, "EXPECTED_RESULT")
})

test_that("commodityName", {
  # tests for the property `commodityName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityName`, "EXPECTED_RESULT")
})

test_that("commodityPriceDate", {
  # tests for the property `commodityPriceDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityPriceDate`, "EXPECTED_RESULT")
})

test_that("commodityPriceDateMonth", {
  # tests for the property `commodityPriceDateMonth` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityPriceDateMonth`, "EXPECTED_RESULT")
})

test_that("commodityPriceDateWeek", {
  # tests for the property `commodityPriceDateWeek` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityPriceDateWeek`, "EXPECTED_RESULT")
})

test_that("commodityPriceDateYear", {
  # tests for the property `commodityPriceDateYear` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityPriceDateYear`, "EXPECTED_RESULT")
})

test_that("commodityUnitID", {
  # tests for the property `commodityUnitID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityUnitID`, "EXPECTED_RESULT")
})

test_that("commodityUnitName", {
  # tests for the property `commodityUnitName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityUnitName`, "EXPECTED_RESULT")
})

test_that("countryName", {
  # tests for the property `countryName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`countryName`, "EXPECTED_RESULT")
})

test_that("currencyID", {
  # tests for the property `currencyID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`currencyID`, "EXPECTED_RESULT")
})

test_that("currencyName", {
  # tests for the property `currencyName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`currencyName`, "EXPECTED_RESULT")
})

test_that("marketID", {
  # tests for the property `marketID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`marketID`, "EXPECTED_RESULT")
})

test_that("marketName", {
  # tests for the property `marketName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`marketName`, "EXPECTED_RESULT")
})

test_that("priceTypeID", {
  # tests for the property `priceTypeID` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`priceTypeID`, "EXPECTED_RESULT")
})

test_that("priceTypeName", {
  # tests for the property `priceTypeName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`priceTypeName`, "EXPECTED_RESULT")
})
