# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FoodSecurityApi")

api_instance <- FoodSecurityApi$new()

test_that("FoodSecurityListGet", {
  # tests for FoodSecurityListGet
  # base path: https://api.wfp.org/vam-data-bridges/1.3.1
  #   [![Generic badge](https://img.shields.io/badge/Maturity%20Level-Production%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
  # @param iso3 character The country ISO3 code (optional)
  # @param year integer  (optional)
  # @param page integer  (optional)
  # @param env character Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (optional)
  # @return [IpcValuePagedResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
