# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WeeklyAggregatedPrice")

model_instance <- WeeklyAggregatedPrice$new()

test_that("adm0Code", {
  # tests for the property `adm0Code` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`adm0Code`, "EXPECTED_RESULT")
})

test_that("commodityDateMonth", {
  # tests for the property `commodityDateMonth` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityDateMonth`, "EXPECTED_RESULT")
})

test_that("commodityDateYear", {
  # tests for the property `commodityDateYear` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityDateYear`, "EXPECTED_RESULT")
})

test_that("commodityId", {
  # tests for the property `commodityId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityId`, "EXPECTED_RESULT")
})

test_that("commodityName", {
  # tests for the property `commodityName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityName`, "EXPECTED_RESULT")
})

test_that("commodityPrice", {
  # tests for the property `commodityPrice` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityPrice`, "EXPECTED_RESULT")
})

test_that("commodityPriceDate", {
  # tests for the property `commodityPriceDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityPriceDate`, "EXPECTED_RESULT")
})

test_that("commodityPriceFlag", {
  # tests for the property `commodityPriceFlag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityPriceFlag`, "EXPECTED_RESULT")
})

test_that("commodityPriceObservations", {
  # tests for the property `commodityPriceObservations` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityPriceObservations`, "EXPECTED_RESULT")
})

test_that("commodityPriceSourceName", {
  # tests for the property `commodityPriceSourceName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityPriceSourceName`, "EXPECTED_RESULT")
})

test_that("commodityUnitId", {
  # tests for the property `commodityUnitId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityUnitId`, "EXPECTED_RESULT")
})

test_that("commodityUnitName", {
  # tests for the property `commodityUnitName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`commodityUnitName`, "EXPECTED_RESULT")
})

test_that("countryISO3", {
  # tests for the property `countryISO3` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`countryISO3`, "EXPECTED_RESULT")
})

test_that("countryName", {
  # tests for the property `countryName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`countryName`, "EXPECTED_RESULT")
})

test_that("currencyId", {
  # tests for the property `currencyId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`currencyId`, "EXPECTED_RESULT")
})

test_that("currencyName", {
  # tests for the property `currencyName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`currencyName`, "EXPECTED_RESULT")
})

test_that("marketId", {
  # tests for the property `marketId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`marketId`, "EXPECTED_RESULT")
})

test_that("marketName", {
  # tests for the property `marketName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`marketName`, "EXPECTED_RESULT")
})

test_that("originalFrequency", {
  # tests for the property `originalFrequency` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`originalFrequency`, "EXPECTED_RESULT")
})

test_that("priceTypeId", {
  # tests for the property `priceTypeId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`priceTypeId`, "EXPECTED_RESULT")
})

test_that("priceTypeName", {
  # tests for the property `priceTypeName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`priceTypeName`, "EXPECTED_RESULT")
})
