# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BadRequestDTO")

model_instance <- BadRequestDTO$new()

test_that("error", {
  # tests for the property `error` (character)
  # The error message returned by the application

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})
