# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Geometry")

model_instance <- Geometry$new()

test_that("area", {
  # tests for the property `area` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`area`, "EXPECTED_RESULT")
})

test_that("boundary", {
  # tests for the property `boundary` (Geometry)

  # uncomment below to test the property
  #expect_equal(model.instance$`boundary`, "EXPECTED_RESULT")
})

test_that("boundaryDimension", {
  # tests for the property `boundaryDimension` (Dimension)

  # uncomment below to test the property
  #expect_equal(model.instance$`boundaryDimension`, "EXPECTED_RESULT")
})

test_that("centroid", {
  # tests for the property `centroid` (Point)

  # uncomment below to test the property
  #expect_equal(model.instance$`centroid`, "EXPECTED_RESULT")
})

test_that("coordinate", {
  # tests for the property `coordinate` (Coordinate)

  # uncomment below to test the property
  #expect_equal(model.instance$`coordinate`, "EXPECTED_RESULT")
})

test_that("coordinates", {
  # tests for the property `coordinates` (array[Coordinate])

  # uncomment below to test the property
  #expect_equal(model.instance$`coordinates`, "EXPECTED_RESULT")
})

test_that("dimension", {
  # tests for the property `dimension` (Dimension)

  # uncomment below to test the property
  #expect_equal(model.instance$`dimension`, "EXPECTED_RESULT")
})

test_that("envelope", {
  # tests for the property `envelope` (Geometry)

  # uncomment below to test the property
  #expect_equal(model.instance$`envelope`, "EXPECTED_RESULT")
})

test_that("envelopeInternal", {
  # tests for the property `envelopeInternal` (Envelope)

  # uncomment below to test the property
  #expect_equal(model.instance$`envelopeInternal`, "EXPECTED_RESULT")
})

test_that("factory", {
  # tests for the property `factory` (GeometryFactory)

  # uncomment below to test the property
  #expect_equal(model.instance$`factory`, "EXPECTED_RESULT")
})

test_that("geometryType", {
  # tests for the property `geometryType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`geometryType`, "EXPECTED_RESULT")
})

test_that("interiorPoint", {
  # tests for the property `interiorPoint` (Point)

  # uncomment below to test the property
  #expect_equal(model.instance$`interiorPoint`, "EXPECTED_RESULT")
})

test_that("isEmpty", {
  # tests for the property `isEmpty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isEmpty`, "EXPECTED_RESULT")
})

test_that("isRectangle", {
  # tests for the property `isRectangle` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isRectangle`, "EXPECTED_RESULT")
})

test_that("isSimple", {
  # tests for the property `isSimple` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isSimple`, "EXPECTED_RESULT")
})

test_that("isValid", {
  # tests for the property `isValid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isValid`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("numGeometries", {
  # tests for the property `numGeometries` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numGeometries`, "EXPECTED_RESULT")
})

test_that("numPoints", {
  # tests for the property `numPoints` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numPoints`, "EXPECTED_RESULT")
})

test_that("ogcGeometryType", {
  # tests for the property `ogcGeometryType` (OgcGeometryType)

  # uncomment below to test the property
  #expect_equal(model.instance$`ogcGeometryType`, "EXPECTED_RESULT")
})

test_that("pointOnSurface", {
  # tests for the property `pointOnSurface` (Point)

  # uncomment below to test the property
  #expect_equal(model.instance$`pointOnSurface`, "EXPECTED_RESULT")
})

test_that("precisionModel", {
  # tests for the property `precisionModel` (PrecisionModel)

  # uncomment below to test the property
  #expect_equal(model.instance$`precisionModel`, "EXPECTED_RESULT")
})

test_that("srid", {
  # tests for the property `srid` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`srid`, "EXPECTED_RESULT")
})

test_that("userData", {
  # tests for the property `userData` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`userData`, "EXPECTED_RESULT")
})
