#' VAM-Data-Bridges
#'
#' API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' The version of the OpenAPI document: 1.3.1
#' Contact: wfp.economicanalysis@wfp.org
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Commodities operations
#' @description CommoditiesApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CommoditiesCategoriesListGet } \emph{ Provides the list of categories. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()  Categories are matched with high level WFP commodity classification at level 1. No mandatory parameter.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } country_code character
#' \item \emph{ @param } category_name character
#' \item \emph{ @param } category_id integer
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{PagedCommodityListDTO} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PagedCommodityListDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ CommoditiesListGet } \emph{ Provide the detailed list of the commodities available in DataBridges platform }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()  COICOP 2018 codes are returned to hierarchically matching categories based on [UN-Statistical Division codes](https://unstats.un.org/unsd/classifications/Econ/). No mandatory parameter.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } country_code character
#' \item \emph{ @param } commodity_name character
#' \item \emph{ @param } commodity_id integer
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{PagedCommodityListDTO} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PagedCommodityListDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CommoditiesCategoriesListGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_country_code <- "country_code_example" # character | The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code (Optional)
#' var_category_name <- "category_name_example" # character | The name, even partial and case insensitive, of a commodity category. (Optional)
#' var_category_id <- 0 # integer | The exact ID of a Commodity, as found in /Commodities/List. (Optional)
#' var_page <- 1 # integer | page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Provides the list of categories.
#' api_instance <- CommoditiesApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$CommoditiesCategoriesListGet(country_code = var_country_code, category_name = var_category_name, category_id = var_category_id, page = var_page, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$CommoditiesCategoriesListGet(country_code = var_country_code, category_name = var_category_name, category_id = var_category_id, page = var_page, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' ####################  CommoditiesListGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_country_code <- "country_code_example" # character | The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code (Optional)
#' var_commodity_name <- "commodity_name_example" # character | The name, even partial and case insensitive, of a commodity (Optional)
#' var_commodity_id <- 0 # integer | The exact ID of a commodity (Optional)
#' var_page <- 1 # integer | page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Provide the detailed list of the commodities available in DataBridges platform
#' api_instance <- CommoditiesApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$CommoditiesListGet(country_code = var_country_code, commodity_name = var_commodity_name, commodity_id = var_commodity_id, page = var_page, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$CommoditiesListGet(country_code = var_country_code, commodity_name = var_commodity_name, commodity_id = var_commodity_id, page = var_page, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
CommoditiesApi <- R6::R6Class(
  "CommoditiesApi",
  public = list(
    api_client = NULL,
    #' Initialize a new CommoditiesApi.
    #'
    #' @description
    #' Initialize a new CommoditiesApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Provides the list of categories.
    #'
    #' @description
    #' Provides the list of categories.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code
    #' @param category_name (optional) The name, even partial and case insensitive, of a commodity category.
    #' @param category_id (optional) The exact ID of a Commodity, as found in /Commodities/List. (default value: 0)
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return PagedCommodityListDTO
    #' @export
    CommoditiesCategoriesListGet = function(country_code = NULL, category_name = NULL, category_id = 0, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$CommoditiesCategoriesListGetWithHttpInfo(country_code, category_name, category_id, page, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Provides the list of categories.
    #'
    #' @description
    #' Provides the list of categories.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code
    #' @param category_name (optional) The name, even partial and case insensitive, of a commodity category.
    #' @param category_id (optional) The exact ID of a Commodity, as found in /Commodities/List. (default value: 0)
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (PagedCommodityListDTO) with additional information such as HTTP status code, headers
    #' @export
    CommoditiesCategoriesListGetWithHttpInfo = function(country_code = NULL, category_name = NULL, category_id = 0, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE







      query_params[["countryCode"]] <- `country_code`

      query_params[["categoryName"]] <- `category_name`

      query_params[["categoryID"]] <- `category_id`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling CommoditiesApi$CommoditiesCategoriesListGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/Commodities/Categories/List"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "PagedCommodityListDTO", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Provide the detailed list of the commodities available in DataBridges platform
    #'
    #' @description
    #' Provide the detailed list of the commodities available in DataBridges platform
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code
    #' @param commodity_name (optional) The name, even partial and case insensitive, of a commodity
    #' @param commodity_id (optional) The exact ID of a commodity (default value: 0)
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return PagedCommodityListDTO
    #' @export
    CommoditiesListGet = function(country_code = NULL, commodity_name = NULL, commodity_id = 0, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$CommoditiesListGetWithHttpInfo(country_code, commodity_name, commodity_id, page, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Provide the detailed list of the commodities available in DataBridges platform
    #'
    #' @description
    #' Provide the detailed list of the commodities available in DataBridges platform
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code
    #' @param commodity_name (optional) The name, even partial and case insensitive, of a commodity
    #' @param commodity_id (optional) The exact ID of a commodity (default value: 0)
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (PagedCommodityListDTO) with additional information such as HTTP status code, headers
    #' @export
    CommoditiesListGetWithHttpInfo = function(country_code = NULL, commodity_name = NULL, commodity_id = 0, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE







      query_params[["countryCode"]] <- `country_code`

      query_params[["commodityName"]] <- `commodity_name`

      query_params[["commodityID"]] <- `commodity_id`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling CommoditiesApi$CommoditiesListGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/Commodities/List"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "PagedCommodityListDTO", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
