#' VAM-Data-Bridges
#'
#' API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' The version of the OpenAPI document: 1.3.1
#' Contact: wfp.economicanalysis@wfp.org
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Currency operations
#' @description CurrencyApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CurrencyListGet } \emph{ Returns the list of currencies available in the internal VAM database, with Currency 3-letter code, matching with ISO 4217. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } country_code character
#' \item \emph{ @param } currency_name character
#' \item \emph{ @param } currency_id integer
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{PagedCurrencyListDTO} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PagedCurrencyListDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ CurrencyUsdIndirectQuotationGet } \emph{ Returns the value of the Exchange rates from Trading Economics, for official rates, and DataViz for unofficial rates. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()  Returns the time series of values of the Exchange rate of the Local Currency for buying 1 USD in the official market. Original frequency for official rates is daily, non-indicated. Unofficial rates are aggregated at national level by the original frequency of collection. For greater detail on unofficial exchange rates, explore the Exchange Rate (unofficial) commodity in Market Prices Prices. No mandatory parameter.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } country_iso3 character
#' \item \emph{ @param } currency_name character
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{UsdIndirectQuotationPagedResult} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : UsdIndirectQuotationPagedResult
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CurrencyListGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_country_code <- "country_code_example" # character | The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (Optional)
#' var_currency_name <- "currency_name_example" # character | Currency 3-letter code, matching with ISO 4217. (Optional)
#' var_currency_id <- 0 # integer | Unique code to identify the currency in internal VAM currencies. (Optional)
#' var_page <- 1 # integer | Page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Returns the list of currencies available in the internal VAM database, with Currency 3-letter code, matching with ISO 4217.
#' api_instance <- CurrencyApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$CurrencyListGet(country_code = var_country_code, currency_name = var_currency_name, currency_id = var_currency_id, page = var_page, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$CurrencyListGet(country_code = var_country_code, currency_name = var_currency_name, currency_id = var_currency_id, page = var_page, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' ####################  CurrencyUsdIndirectQuotationGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_country_iso3 <- "" # character | The code to identify the country. Must be a ISO-3166 Alpha 3 code. (Optional)
#' var_currency_name <- "" # character | the ISO3 code for the currency, based on ISO4217 (Optional)
#' var_page <- 1 # integer | Page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Returns the value of the Exchange rates from Trading Economics, for official rates, and DataViz for unofficial rates.
#' api_instance <- CurrencyApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$CurrencyUsdIndirectQuotationGet(country_iso3 = var_country_iso3, currency_name = var_currency_name, page = var_page, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$CurrencyUsdIndirectQuotationGet(country_iso3 = var_country_iso3, currency_name = var_currency_name, page = var_page, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
CurrencyApi <- R6::R6Class(
  "CurrencyApi",
  public = list(
    api_client = NULL,
    #' Initialize a new CurrencyApi.
    #'
    #' @description
    #' Initialize a new CurrencyApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Returns the list of currencies available in the internal VAM database, with Currency 3-letter code, matching with ISO 4217.
    #'
    #' @description
    #' Returns the list of currencies available in the internal VAM database, with Currency 3-letter code, matching with ISO 4217.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param currency_name (optional) Currency 3-letter code, matching with ISO 4217.
    #' @param currency_id (optional) Unique code to identify the currency in internal VAM currencies. (default value: 0)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return PagedCurrencyListDTO
    #' @export
    CurrencyListGet = function(country_code = NULL, currency_name = NULL, currency_id = 0, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$CurrencyListGetWithHttpInfo(country_code, currency_name, currency_id, page, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Returns the list of currencies available in the internal VAM database, with Currency 3-letter code, matching with ISO 4217.
    #'
    #' @description
    #' Returns the list of currencies available in the internal VAM database, with Currency 3-letter code, matching with ISO 4217.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param currency_name (optional) Currency 3-letter code, matching with ISO 4217.
    #' @param currency_id (optional) Unique code to identify the currency in internal VAM currencies. (default value: 0)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (PagedCurrencyListDTO) with additional information such as HTTP status code, headers
    #' @export
    CurrencyListGetWithHttpInfo = function(country_code = NULL, currency_name = NULL, currency_id = 0, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE







      query_params[["countryCode"]] <- `country_code`

      query_params[["currencyName"]] <- `currency_name`

      query_params[["currencyID"]] <- `currency_id`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling CurrencyApi$CurrencyListGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/Currency/List"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "PagedCurrencyListDTO", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Returns the value of the Exchange rates from Trading Economics, for official rates, and DataViz for unofficial rates.
    #'
    #' @description
    #' Returns the value of the Exchange rates from Trading Economics, for official rates, and DataViz for unofficial rates.
    #'
    #' @param country_iso3 (optional) The code to identify the country. Must be a ISO-3166 Alpha 3 code. (default value: "")
    #' @param currency_name (optional) the ISO3 code for the currency, based on ISO4217 (default value: "")
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return UsdIndirectQuotationPagedResult
    #' @export
    CurrencyUsdIndirectQuotationGet = function(country_iso3 = "", currency_name = "", page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$CurrencyUsdIndirectQuotationGetWithHttpInfo(country_iso3, currency_name, page, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Returns the value of the Exchange rates from Trading Economics, for official rates, and DataViz for unofficial rates.
    #'
    #' @description
    #' Returns the value of the Exchange rates from Trading Economics, for official rates, and DataViz for unofficial rates.
    #'
    #' @param country_iso3 (optional) The code to identify the country. Must be a ISO-3166 Alpha 3 code. (default value: "")
    #' @param currency_name (optional) the ISO3 code for the currency, based on ISO4217 (default value: "")
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (UsdIndirectQuotationPagedResult) with additional information such as HTTP status code, headers
    #' @export
    CurrencyUsdIndirectQuotationGetWithHttpInfo = function(country_iso3 = "", currency_name = "", page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE






      query_params[["countryIso3"]] <- `country_iso3`

      query_params[["currencyName"]] <- `currency_name`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling CurrencyApi$CurrencyUsdIndirectQuotationGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/Currency/UsdIndirectQuotation"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "UsdIndirectQuotationPagedResult", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
