#' VAM-Data-Bridges
#'
#' API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' The version of the OpenAPI document: 1.3.1
#' Contact: wfp.economicanalysis@wfp.org
#' Generated by: https://openapi-generator.tech
#'
#' databridges API Class
#'
#' A single point of access to the databridges API.
#'
#' NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
#' Ref: https://openapi-generator.tech
#' Do not edit the class manually.
#'
#' @docType class
#' @title ApiClient
#' @description ApiClient Class
#' @format An \code{R6Class} generator object
#' @field api_client API client
#' @field commodities_api an instance of CommoditiesApi
#' @field commodity_units_api an instance of CommodityUnitsApi
#' @field currency_api an instance of CurrencyApi
#' @field economic_data_api an instance of EconomicDataApi
#' @field food_security_api an instance of FoodSecurityApi
#' @field gorp_api an instance of GorpApi
#' @field market_prices_api an instance of MarketPricesApi
#' @field markets_api an instance of MarketsApi
#' @field rpme_api an instance of RpmeApi
#' @field surveys_api an instance of SurveysApi
#' @field xls_forms_api an instance of XlsFormsApi
#' @export
databridges_api <- R6::R6Class(
  "databridges_api",
  public = list(
    api_client = NULL,
    commodities_api = NULL,
    commodity_units_api = NULL,
    currency_api = NULL,
    economic_data_api = NULL,
    food_security_api = NULL,
    gorp_api = NULL,
    market_prices_api = NULL,
    markets_api = NULL,
    rpme_api = NULL,
    surveys_api = NULL,
    xls_forms_api = NULL,
    #' Initialize a new databridges API Class.
    #'
    #' @description
    #' Initialize a new databridges API Class.
    #'
    #' @param api_client An instance of API client (optional).
    #' @export
    initialize = function(api_client) {
      if (missing(api_client)) {
        self$api_client <- ApiClient$new()
      } else {
        self$api_client <- api_client
      } 

      self$commodities_api <- CommoditiesApi$new(self$api_client)

      self$commodity_units_api <- CommodityUnitsApi$new(self$api_client)

      self$currency_api <- CurrencyApi$new(self$api_client)

      self$economic_data_api <- EconomicDataApi$new(self$api_client)

      self$food_security_api <- FoodSecurityApi$new(self$api_client)

      self$gorp_api <- GorpApi$new(self$api_client)

      self$market_prices_api <- MarketPricesApi$new(self$api_client)

      self$markets_api <- MarketsApi$new(self$api_client)

      self$rpme_api <- RpmeApi$new(self$api_client)

      self$surveys_api <- SurveysApi$new(self$api_client)

      self$xls_forms_api <- XlsFormsApi$new(self$api_client)

    }
  )
)
