#' VAM-Data-Bridges
#'
#' API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' The version of the OpenAPI document: 1.3.1
#' Contact: wfp.economicanalysis@wfp.org
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title EconomicData operations
#' @description EconomicDataApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ EconomicDataIndicatorListGet } \emph{ Returns the lists of indicators. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()  Returns the lists of indicators for which Vulnerability Analysis and Mapping - Economic and Market Analysis Unit has redistribution licensing from Trading Economics. No mandatory parameter.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } page integer
#' \item \emph{ @param } indicator_name character
#' \item \emph{ @param } iso3 character
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{EconomicIndicatorPropertyPagedResult} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : EconomicIndicatorPropertyPagedResult
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Not Found
#'
#' \item return type : ProblemDetails
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ EconomicDataIndicatorNameGet } \emph{ Returns the time series of values for different indicators. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()  Indicator name as retrieved from /EconomicData/IndicatorList is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } indicator_name character
#' \item \emph{ @param } page integer
#' \item \emph{ @param } iso3 character
#' \item \emph{ @param } start_date character
#' \item \emph{ @param } end_date character
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : data.frame
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Not Found
#'
#' \item return type : ProblemDetails
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  EconomicDataIndicatorListGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_page <- 1 # integer | Page number for paged results (Optional)
#' var_indicator_name <- "" # character | Unique indicator name. (Optional)
#' var_iso3 <- "" # character | The code to identify the country. Must be a ISO-3166 Alpha 3 code. (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Returns the lists of indicators.
#' api_instance <- EconomicDataApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$EconomicDataIndicatorListGet(page = var_page, indicator_name = var_indicator_name, iso3 = var_iso3, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$EconomicDataIndicatorListGet(page = var_page, indicator_name = var_indicator_name, iso3 = var_iso3, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' ####################  EconomicDataIndicatorNameGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_indicator_name <- "indicator_name_example" # character | Name of the indicator as found in /EconomicData/IndicatorList.
#' var_page <- 1 # integer | Page number for paged results (Optional)
#' var_iso3 <- "" # character | The code to identify the country. Must be a ISO-3166 Alpha 3 code. (Optional)
#' var_start_date <- "start_date_example" # character | Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_end_date <- "end_date_example" # character | Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Returns the time series of values for different indicators.
#' api_instance <- EconomicDataApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$EconomicDataIndicatorNameGet(var_indicator_name, page = var_page, iso3 = var_iso3, start_date = var_start_date, end_date = var_end_date, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$EconomicDataIndicatorNameGet(var_indicator_name, page = var_page, iso3 = var_iso3, start_date = var_start_date, end_date = var_end_date, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
EconomicDataApi <- R6::R6Class(
  "EconomicDataApi",
  public = list(
    api_client = NULL,
    #' Initialize a new EconomicDataApi.
    #'
    #' @description
    #' Initialize a new EconomicDataApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Returns the lists of indicators.
    #'
    #' @description
    #' Returns the lists of indicators.
    #'
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param indicator_name (optional) Unique indicator name. (default value: "")
    #' @param iso3 (optional) The code to identify the country. Must be a ISO-3166 Alpha 3 code. (default value: "")
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return EconomicIndicatorPropertyPagedResult
    #' @export
    EconomicDataIndicatorListGet = function(page = 1, indicator_name = "", iso3 = "", format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$EconomicDataIndicatorListGetWithHttpInfo(page, indicator_name, iso3, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Returns the lists of indicators.
    #'
    #' @description
    #' Returns the lists of indicators.
    #'
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param indicator_name (optional) Unique indicator name. (default value: "")
    #' @param iso3 (optional) The code to identify the country. Must be a ISO-3166 Alpha 3 code. (default value: "")
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (EconomicIndicatorPropertyPagedResult) with additional information such as HTTP status code, headers
    #' @export
    EconomicDataIndicatorListGetWithHttpInfo = function(page = 1, indicator_name = "", iso3 = "", format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE






      query_params[["page"]] <- `page`

      query_params[["indicatorName"]] <- `indicator_name`

      query_params[["iso3"]] <- `iso3`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling EconomicDataApi$EconomicDataIndicatorListGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/EconomicData/IndicatorList"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "EconomicIndicatorPropertyPagedResult", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Returns the time series of values for different indicators.
    #'
    #' @description
    #' Returns the time series of values for different indicators.
    #'
    #' @param indicator_name Name of the indicator as found in /EconomicData/IndicatorList.
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param iso3 (optional) The code to identify the country. Must be a ISO-3166 Alpha 3 code. (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return data.frame
    #' @export
    EconomicDataIndicatorNameGet = function(indicator_name, page = 1, iso3 = "", start_date = NULL, end_date = NULL, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$EconomicDataIndicatorNameGetWithHttpInfo(indicator_name, page, iso3, start_date, end_date, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Returns the time series of values for different indicators.
    #'
    #' @description
    #' Returns the time series of values for different indicators.
    #'
    #' @param indicator_name Name of the indicator as found in /EconomicData/IndicatorList.
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param iso3 (optional) The code to identify the country. Must be a ISO-3166 Alpha 3 code. (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (data.frame) with additional information such as HTTP status code, headers
    #' @export
    EconomicDataIndicatorNameGetWithHttpInfo = function(indicator_name, page = 1, iso3 = "", start_date = NULL, end_date = NULL, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`indicator_name`)) {
        stop("Missing required parameter `indicator_name`.")
      }








      query_params[["page"]] <- `page`

      query_params[["iso3"]] <- `iso3`

      query_params[["startDate"]] <- `start_date`

      query_params[["endDate"]] <- `end_date`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling EconomicDataApi$EconomicDataIndicatorNameGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/EconomicData/{indicatorName}"
      if (!missing(`indicator_name`)) {
        local_var_url_path <- gsub("\\{indicatorName\\}", URLencode(as.character(`indicator_name`), reserved = TRUE), local_var_url_path)
      }

      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "data.frame", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
