#' VAM-Data-Bridges
#'
#' API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' The version of the OpenAPI document: 1.3.1
#' Contact: wfp.economicanalysis@wfp.org
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Gorp operations
#' @description GorpApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ GorpLatestGet } \emph{ Return the latest dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } page integer
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{GorpValueWithChangesPagedResult} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : GorpValueWithChangesPagedResult
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GorpListGet } \emph{ Return the full dataset of number of acutely food insecure (in millions) based on WFP Global Operational Response Plan. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } page integer
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{GorpValueWithChangesPagedResult} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : GorpValueWithChangesPagedResult
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  GorpLatestGet  ####################
#'
#' library(databridges)
#' var_page <- 1 # integer |  (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Return the latest dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan.
#' api_instance <- databridges_api$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GorpLatestGet(page = var_page, env = var_envdata_file = "result.txt")
#' result <- api_instance$gorp_api$GorpLatestGet(page = var_page, env = var_env)
#' dput(result)
#'
#'
#' ####################  GorpListGet  ####################
#'
#' library(databridges)
#' var_page <- 1 # integer |  (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Return the full dataset of number of acutely food insecure (in millions) based on WFP Global Operational Response Plan.
#' api_instance <- databridges_api$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GorpListGet(page = var_page, env = var_envdata_file = "result.txt")
#' result <- api_instance$gorp_api$GorpListGet(page = var_page, env = var_env)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
GorpApi <- R6::R6Class(
  "GorpApi",
  public = list(
    api_client = NULL,
    #' Initialize a new GorpApi.
    #'
    #' @description
    #' Initialize a new GorpApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Return the latest dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan.
    #'
    #' @description
    #' Return the latest dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan.
    #'
    #' @param page (optional) No description (default value: 1)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return GorpValueWithChangesPagedResult
    #' @export
    GorpLatestGet = function(page = 1, env = NULL, data_file = NULL, ...) {
      local_var_response <- self$GorpLatestGetWithHttpInfo(page, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Return the latest dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan.
    #'
    #' @description
    #' Return the latest dataset of number of acutely food insecure (in millions)  based on WFP Global Operational Response Plan.
    #'
    #' @param page (optional) No description (default value: 1)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (GorpValueWithChangesPagedResult) with additional information such as HTTP status code, headers
    #' @export
    GorpLatestGetWithHttpInfo = function(page = 1, env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE



      query_params[["page"]] <- `page`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling GorpApi$GorpLatestGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/Gorp/Latest"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "GorpValueWithChangesPagedResult", loadNamespace("databridges")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Return the full dataset of number of acutely food insecure (in millions) based on WFP Global Operational Response Plan.
    #'
    #' @description
    #' Return the full dataset of number of acutely food insecure (in millions) based on WFP Global Operational Response Plan.
    #'
    #' @param page (optional) No description (default value: 1)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return GorpValueWithChangesPagedResult
    #' @export
    GorpListGet = function(page = 1, env = NULL, data_file = NULL, ...) {
      local_var_response <- self$GorpListGetWithHttpInfo(page, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Return the full dataset of number of acutely food insecure (in millions) based on WFP Global Operational Response Plan.
    #'
    #' @description
    #' Return the full dataset of number of acutely food insecure (in millions) based on WFP Global Operational Response Plan.
    #'
    #' @param page (optional) No description (default value: 1)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (GorpValueWithChangesPagedResult) with additional information such as HTTP status code, headers
    #' @export
    GorpListGetWithHttpInfo = function(page = 1, env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE



      query_params[["page"]] <- `page`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling GorpApi$GorpListGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/Gorp/List"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "GorpValueWithChangesPagedResult", loadNamespace("databridges")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
