#' VAM-Data-Bridges
#'
#' API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' The version of the OpenAPI document: 1.3.1
#' Contact: wfp.economicanalysis@wfp.org
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title MarketPrices operations
#' @description MarketPricesApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ MarketPricesAlpsGet } \emph{ Returns time series values of ALPS and PEWI. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()  Returns the full time series of the Alert for Price Spikes (ALPS) and the value of the Price Early Warning Index (PEWI). Methodology is available in [DataViz](https://dataviz.vam.wfp.org/) and [VAM-Resource Centre](https://resources.vam.wfp.org/). Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } country_code character
#' \item \emph{ @param } market_id integer
#' \item \emph{ @param } commodity_id integer
#' \item \emph{ @param } price_type_name character
#' \item \emph{ @param } currency_id integer
#' \item \emph{ @param } price_flag character
#' \item \emph{ @param } start_date character
#' \item \emph{ @param } end_date character
#' \item \emph{ @param } latest_value_only character
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{ViewExtendedAlpsValuePagedResult} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ViewExtendedAlpsValuePagedResult
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MarketPricesPriceDailyGet } \emph{ Returns a daily time series of commodity market prices. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()  This is the highest frequency available. Data is flagged according to its pre-processing characteristics. Actual data is collected originally with daily frequency; aggregated data returns an empty list; imputed data is an estimation of missing values in the time series, obtained through the R Amelia-II package;        forecasted data is a six months prediction obtained through different methods, which are reported in the API.  For country specific meta-data please refer to documentation available in DataLibrary. For specific methodological notes on forecasts and imputations refer to the dedicated page in DataViz.  Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } country_code character
#' \item \emph{ @param } market_id integer
#' \item \emph{ @param } commodity_id integer
#' \item \emph{ @param } price_type_name character
#' \item \emph{ @param } currency_id integer
#' \item \emph{ @param } price_flag character
#' \item \emph{ @param } start_date character
#' \item \emph{ @param } end_date character
#' \item \emph{ @param } latest_value_only character
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{ViewExtendedAggregatedPricePagedResult} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ViewExtendedAggregatedPricePagedResult
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MarketPricesPriceMonthlyGet } \emph{ Returns a monthly time series of commodity market prices. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()  This is the lowest frequency available and the most complete data source. Data is flagged according to its pre-processing characteristics. actual data is collected originally with monthly frequency; aggregated data is collected with higher frequency (daily or weekly) averaged through a weighted mean to monthly; imputed data is an estimation of missing values in the time series, obtained through the R Amelia-II package; forecasted data is a six months prediction obtained through different methods, which are reported in the API. For country specific meta-data please refer to documentation available in [DataLibrary](https://datalib.vam.wfp.org/). For specific methodological notes on forecasts and imputations refer to the dedicated page in [DataViz](https://dataviz.vam.wfp.org/). Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } country_code character
#' \item \emph{ @param } market_id integer
#' \item \emph{ @param } commodity_id integer
#' \item \emph{ @param } price_type_name character
#' \item \emph{ @param } currency_id integer
#' \item \emph{ @param } price_flag character
#' \item \emph{ @param } start_date character
#' \item \emph{ @param } end_date character
#' \item \emph{ @param } latest_value_only character
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{ViewExtendedAggregatedPricePagedResult} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ViewExtendedAggregatedPricePagedResult
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MarketPricesPriceRawGet } \emph{ Returns original commodity market prices }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Restricted-yellow)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Official\%20Use\%20Only-yellow)]()  ### This endpoint is restricted, it requires the scope: \"vamdatabridges_marketprices-priceraw_get\"  Restricted endpoint. Returns the original data with the entire Commodity Price Metadata as inserted by the focal point, which might contain sensitive or personal informatio. Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } country_code character
#' \item \emph{ @param } market_id integer
#' \item \emph{ @param } commodity_id integer
#' \item \emph{ @param } price_type_name character
#' \item \emph{ @param } currency_id integer
#' \item \emph{ @param } price_flag character
#' \item \emph{ @param } start_date character
#' \item \emph{ @param } end_date character
#' \item \emph{ @param } latest_value_only character
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{PagedCommodityPriceListDTO} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PagedCommodityPriceListDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MarketPricesPriceWeeklyGet } \emph{ Returns a weekly time series of commodity market prices. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()  Weeks used as reference are the International Organization for Standardization (ISO) week-numbering year (ISO-8601). Data is flagged according to its pre-processing characteristics. Aactual data is collected originally with weekly frequency; aggregated data is collected with higher frequency (daily) averaged through a weighted mean to weekly; imputed data is an estimation of missing values in the time series, obtained through the R Amelia-II package; forecasted data is a six months prediction obtained through different methods, which are reported in the API. For country specific meta-data please refer to documentation available in [DataLibrary](https://datalib.vam.wfp.org/). For specific methodological notes on forecasts and imputations refer to the dedicated page in [DataViz](https://dataviz.vam.wfp.org/). Country code, either ISO-3166 Alpha 3 code or the VAM internal admin0code is mandatory.    **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } country_code character
#' \item \emph{ @param } market_id integer
#' \item \emph{ @param } commodity_id integer
#' \item \emph{ @param } price_type_name character
#' \item \emph{ @param } currency_id integer
#' \item \emph{ @param } price_flag character
#' \item \emph{ @param } start_date character
#' \item \emph{ @param } end_date character
#' \item \emph{ @param } latest_value_only character
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{PagedCommodityWeeklyAggregatedPriceListDTO} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PagedCommodityWeeklyAggregatedPriceListDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  MarketPricesAlpsGet  ####################
#'
#' library(databridges)
#' var_country_code <- "country_code_example" # character | The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (Optional)
#' var_market_id <- 0 # integer | Unique ID of a Market, as found in /Markets/GeoJSONList (Optional)
#' var_commodity_id <- 0 # integer | The exact ID of a Commodity, as found in /Commodities/List (Optional)
#' var_price_type_name <- "" # character | Price type: [retail|wholesale|farmgate] (Optional)
#' var_currency_id <- 0 # integer | The exact ID of a currency, as found in /Currency/List (Optional)
#' var_price_flag <- "" # character | Type of price data: [actual|aggregate|estimated|forecasted] (Optional)
#' var_start_date <- "start_date_example" # character | Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_end_date <- "end_date_example" # character | Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_latest_value_only <- FALSE # character | [TRUE|FALSE] (Optional)
#' var_page <- 1 # integer | Page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Returns time series values of ALPS and PEWI.
#' api_instance <- databridges_api$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$MarketPricesAlpsGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$market_prices_api$MarketPricesAlpsGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' ####################  MarketPricesPriceDailyGet  ####################
#'
#' library(databridges)
#' var_country_code <- "country_code_example" # character | The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (Optional)
#' var_market_id <- 0 # integer | Unique ID of a Market, as found in /Markets/GeoJSONList (Optional)
#' var_commodity_id <- 0 # integer | The exact ID of a Commodity, as found in /Commodities/List (Optional)
#' var_price_type_name <- "" # character | Price type: [retail|wholesale|farmgate] (Optional)
#' var_currency_id <- 0 # integer | The exact ID of a currency, as found in /Currency/List (Optional)
#' var_price_flag <- "" # character | Type of price data: [actual|aggregate|estimated|forecasted] (Optional)
#' var_start_date <- "start_date_example" # character | Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_end_date <- "end_date_example" # character | Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_latest_value_only <- FALSE # character | [TRUE|FALSE] (Optional)
#' var_page <- 1 # integer | Page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Returns a daily time series of commodity market prices.
#' api_instance <- databridges_api$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$MarketPricesPriceDailyGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$market_prices_api$MarketPricesPriceDailyGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' ####################  MarketPricesPriceMonthlyGet  ####################
#'
#' library(databridges)
#' var_country_code <- "country_code_example" # character | The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (Optional)
#' var_market_id <- 0 # integer | Unique ID of a Market, as found in /Markets/GeoJSONList (Optional)
#' var_commodity_id <- 0 # integer | The exact ID of a Commodity, as found in /Commodities/List (Optional)
#' var_price_type_name <- "" # character | Price type: [retail|wholesale|farmgate] (Optional)
#' var_currency_id <- 0 # integer | The exact ID of a currency, as found in /Currency/List (Optional)
#' var_price_flag <- "" # character | Type of price data: [actual|aggregate|estimated|forecasted] (Optional)
#' var_start_date <- "start_date_example" # character | Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_end_date <- "end_date_example" # character | Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_latest_value_only <- FALSE # character | [TRUE|FALSE] (Optional)
#' var_page <- 1 # integer | Page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Returns a monthly time series of commodity market prices.
#' api_instance <- databridges_api$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$MarketPricesPriceMonthlyGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$market_prices_api$MarketPricesPriceMonthlyGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' ####################  MarketPricesPriceRawGet  ####################
#'
#' library(databridges)
#' var_country_code <- "country_code_example" # character | The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (Optional)
#' var_market_id <- 0 # integer | Unique ID of a Market, as found in /Markets/GeoJSONList (Optional)
#' var_commodity_id <- 0 # integer | The exact ID of a Commodity, as found in /Commodities/List (Optional)
#' var_price_type_name <- "" # character | Price type: [retail|wholesale|farmgate] (Optional)
#' var_currency_id <- 0 # integer | The exact ID of a currency, as found in /Currency/List (Optional)
#' var_price_flag <- "" # character | Type of price data: [actual|aggregate|estimated|forecasted] (Optional)
#' var_start_date <- "start_date_example" # character | Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_end_date <- "end_date_example" # character | Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_latest_value_only <- FALSE # character | [TRUE|FALSE] (Optional)
#' var_page <- 1 # integer | Page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Returns original commodity market prices
#' api_instance <- databridges_api$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$MarketPricesPriceRawGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$market_prices_api$MarketPricesPriceRawGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' ####################  MarketPricesPriceWeeklyGet  ####################
#'
#' library(databridges)
#' var_country_code <- "country_code_example" # character | The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code. (Optional)
#' var_market_id <- 0 # integer | Unique ID of a Market, as found in /Markets/GeoJSONList (Optional)
#' var_commodity_id <- 0 # integer | The exact ID of a Commodity, as found in /Commodities/List (Optional)
#' var_price_type_name <- "" # character | Price type: [retail|wholesale|farmgate] (Optional)
#' var_currency_id <- 0 # integer | The exact ID of a currency, as found in /Currency/List (Optional)
#' var_price_flag <- "" # character | Type of price data: [actual|aggregate|estimated|forecasted] (Optional)
#' var_start_date <- "start_date_example" # character | Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_end_date <- "end_date_example" # character | Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24) (Optional)
#' var_latest_value_only <- FALSE # character | [TRUE|FALSE] (Optional)
#' var_page <- 1 # integer | Page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Returns a weekly time series of commodity market prices.
#' api_instance <- databridges_api$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$MarketPricesPriceWeeklyGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_envdata_file = "result.txt")
#' result <- api_instance$market_prices_api$MarketPricesPriceWeeklyGet(country_code = var_country_code, market_id = var_market_id, commodity_id = var_commodity_id, price_type_name = var_price_type_name, currency_id = var_currency_id, price_flag = var_price_flag, start_date = var_start_date, end_date = var_end_date, latest_value_only = var_latest_value_only, page = var_page, format = var_format, env = var_env)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
MarketPricesApi <- R6::R6Class(
  "MarketPricesApi",
  public = list(
    api_client = NULL,
    #' Initialize a new MarketPricesApi.
    #'
    #' @description
    #' Initialize a new MarketPricesApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Returns time series values of ALPS and PEWI.
    #'
    #' @description
    #' Returns time series values of ALPS and PEWI.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return ViewExtendedAlpsValuePagedResult
    #' @export
    MarketPricesAlpsGet = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$MarketPricesAlpsGetWithHttpInfo(country_code, market_id, commodity_id, price_type_name, currency_id, price_flag, start_date, end_date, latest_value_only, page, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Returns time series values of ALPS and PEWI.
    #'
    #' @description
    #' Returns time series values of ALPS and PEWI.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (ViewExtendedAlpsValuePagedResult) with additional information such as HTTP status code, headers
    #' @export
    MarketPricesAlpsGetWithHttpInfo = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE













      query_params[["countryCode"]] <- `country_code`

      query_params[["marketID"]] <- `market_id`

      query_params[["commodityID"]] <- `commodity_id`

      query_params[["priceTypeName"]] <- `price_type_name`

      query_params[["currencyID"]] <- `currency_id`

      query_params[["priceFlag"]] <- `price_flag`

      query_params[["startDate"]] <- `start_date`

      query_params[["endDate"]] <- `end_date`

      query_params[["latestValueOnly"]] <- `latest_value_only`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling MarketPricesApi$MarketPricesAlpsGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/MarketPrices/Alps"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "ViewExtendedAlpsValuePagedResult", loadNamespace("databridges")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Returns a daily time series of commodity market prices.
    #'
    #' @description
    #' Returns a daily time series of commodity market prices.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return ViewExtendedAggregatedPricePagedResult
    #' @export
    MarketPricesPriceDailyGet = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$MarketPricesPriceDailyGetWithHttpInfo(country_code, market_id, commodity_id, price_type_name, currency_id, price_flag, start_date, end_date, latest_value_only, page, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Returns a daily time series of commodity market prices.
    #'
    #' @description
    #' Returns a daily time series of commodity market prices.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (ViewExtendedAggregatedPricePagedResult) with additional information such as HTTP status code, headers
    #' @export
    MarketPricesPriceDailyGetWithHttpInfo = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE













      query_params[["countryCode"]] <- `country_code`

      query_params[["marketID"]] <- `market_id`

      query_params[["commodityID"]] <- `commodity_id`

      query_params[["priceTypeName"]] <- `price_type_name`

      query_params[["currencyID"]] <- `currency_id`

      query_params[["priceFlag"]] <- `price_flag`

      query_params[["startDate"]] <- `start_date`

      query_params[["endDate"]] <- `end_date`

      query_params[["latestValueOnly"]] <- `latest_value_only`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling MarketPricesApi$MarketPricesPriceDailyGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/MarketPrices/PriceDaily"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "ViewExtendedAggregatedPricePagedResult", loadNamespace("databridges")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Returns a monthly time series of commodity market prices.
    #'
    #' @description
    #' Returns a monthly time series of commodity market prices.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return ViewExtendedAggregatedPricePagedResult
    #' @export
    MarketPricesPriceMonthlyGet = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$MarketPricesPriceMonthlyGetWithHttpInfo(country_code, market_id, commodity_id, price_type_name, currency_id, price_flag, start_date, end_date, latest_value_only, page, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Returns a monthly time series of commodity market prices.
    #'
    #' @description
    #' Returns a monthly time series of commodity market prices.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (ViewExtendedAggregatedPricePagedResult) with additional information such as HTTP status code, headers
    #' @export
    MarketPricesPriceMonthlyGetWithHttpInfo = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE













      query_params[["countryCode"]] <- `country_code`

      query_params[["marketID"]] <- `market_id`

      query_params[["commodityID"]] <- `commodity_id`

      query_params[["priceTypeName"]] <- `price_type_name`

      query_params[["currencyID"]] <- `currency_id`

      query_params[["priceFlag"]] <- `price_flag`

      query_params[["startDate"]] <- `start_date`

      query_params[["endDate"]] <- `end_date`

      query_params[["latestValueOnly"]] <- `latest_value_only`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling MarketPricesApi$MarketPricesPriceMonthlyGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/MarketPrices/PriceMonthly"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "ViewExtendedAggregatedPricePagedResult", loadNamespace("databridges")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Returns original commodity market prices
    #'
    #' @description
    #' Returns original commodity market prices
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return PagedCommodityPriceListDTO
    #' @export
    MarketPricesPriceRawGet = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$MarketPricesPriceRawGetWithHttpInfo(country_code, market_id, commodity_id, price_type_name, currency_id, price_flag, start_date, end_date, latest_value_only, page, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Returns original commodity market prices
    #'
    #' @description
    #' Returns original commodity market prices
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (PagedCommodityPriceListDTO) with additional information such as HTTP status code, headers
    #' @export
    MarketPricesPriceRawGetWithHttpInfo = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE













      query_params[["countryCode"]] <- `country_code`

      query_params[["marketID"]] <- `market_id`

      query_params[["commodityID"]] <- `commodity_id`

      query_params[["priceTypeName"]] <- `price_type_name`

      query_params[["currencyID"]] <- `currency_id`

      query_params[["priceFlag"]] <- `price_flag`

      query_params[["startDate"]] <- `start_date`

      query_params[["endDate"]] <- `end_date`

      query_params[["latestValueOnly"]] <- `latest_value_only`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling MarketPricesApi$MarketPricesPriceRawGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/MarketPrices/PriceRaw"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- "vamdatabridges_marketprices-priceraw_get"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "PagedCommodityPriceListDTO", loadNamespace("databridges")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Returns a weekly time series of commodity market prices.
    #'
    #' @description
    #' Returns a weekly time series of commodity market prices.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return PagedCommodityWeeklyAggregatedPriceListDTO
    #' @export
    MarketPricesPriceWeeklyGet = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      local_var_response <- self$MarketPricesPriceWeeklyGetWithHttpInfo(country_code, market_id, commodity_id, price_type_name, currency_id, price_flag, start_date, end_date, latest_value_only, page, format, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Returns a weekly time series of commodity market prices.
    #'
    #' @description
    #' Returns a weekly time series of commodity market prices.
    #'
    #' @param country_code (optional) The code to identify the country. It can be a ISO-3166 Alpha 3 code or the VAM internal admin0code.
    #' @param market_id (optional) Unique ID of a Market, as found in /Markets/GeoJSONList (default value: 0)
    #' @param commodity_id (optional) The exact ID of a Commodity, as found in /Commodities/List (default value: 0)
    #' @param price_type_name (optional) Price type: [retail|wholesale|farmgate] (default value: "")
    #' @param currency_id (optional) The exact ID of a currency, as found in /Currency/List (default value: 0)
    #' @param price_flag (optional) Type of price data: [actual|aggregate|estimated|forecasted] (default value: "")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \\\"-\\\" month \\\"-\\\" day (e.g. 2020/06/24)
    #' @param latest_value_only (optional) [TRUE|FALSE] (default value: FALSE)
    #' @param page (optional) Page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (PagedCommodityWeeklyAggregatedPriceListDTO) with additional information such as HTTP status code, headers
    #' @export
    MarketPricesPriceWeeklyGetWithHttpInfo = function(country_code = NULL, market_id = 0, commodity_id = 0, price_type_name = "", currency_id = 0, price_flag = "", start_date = NULL, end_date = NULL, latest_value_only = FALSE, page = 1, format = "json", env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE













      query_params[["countryCode"]] <- `country_code`

      query_params[["marketID"]] <- `market_id`

      query_params[["commodityID"]] <- `commodity_id`

      query_params[["priceTypeName"]] <- `price_type_name`

      query_params[["currencyID"]] <- `currency_id`

      query_params[["priceFlag"]] <- `price_flag`

      query_params[["startDate"]] <- `start_date`

      query_params[["endDate"]] <- `end_date`

      query_params[["latestValueOnly"]] <- `latest_value_only`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling MarketPricesApi$MarketPricesPriceWeeklyGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/MarketPrices/PriceWeekly"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "PagedCommodityWeeklyAggregatedPriceListDTO", loadNamespace("databridges")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
