#' VAM-Data-Bridges
#'
#' API Documentation of the **DataBridges** platform: https://databridges.vam.wfp.org/. For API discussions and details: #api-integration-vam-data-bridges on Slack, [Teams channel](https://teams.microsoft.com/l/team/19%3a4ca595f7681f4ffa8a86b7af58832e8d%40thread.skype/conversations?groupId=cbd1e508-c6e8-459d-96b7-6cac3039c42c&tenantId=462ad9ae-d7d9-4206-b874-71b1e079776f) **API Integration** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' The version of the OpenAPI document: 1.3.1
#' Contact: wfp.economicanalysis@wfp.org
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Surveys operations
#' @description SurveysApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ MFISurveysBaseDataGet } \emph{ Get data that includes the core Market Functionality Index (MFI) fields only by Survey ID }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } survey_id integer
#' \item \emph{ @param } page integer
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{SurveyDetailsDTO} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : SurveyDetailsDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Not Found
#'
#' \item return type : ProblemDetails
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MFISurveysFullDataGet } \emph{ Get a full dataset that includes all the fields included in the survey in addition to the core Market Functionality Index (MFI) fields by Survey ID. To access this data, please contact global.mfi@wfp.org for authorization. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Restricted-yellow)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Official\%20Use\%20Only-yellow)]()  ### This endpoint is restricted, it requires the scope: \"vamdatabridges_mfi-surveys-fulldata_get\"      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } survey_id integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } page integer
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{SurveyDetailsDTO} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : SurveyDetailsDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Not Found
#'
#' \item return type : ProblemDetails
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MFISurveysGet } \emph{ Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all MFI surveys conducted in a country. A date of reference, SurveyDate, for the data collection is set by the officer responsible of the upload for each survey. }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } adm0_code integer
#' \item \emph{ @param } page integer
#' \item \emph{ @param } start_date character
#' \item \emph{ @param } end_date character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } list( \link{PagedSurveyListDTO} ) \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : array[PagedSurveyListDTO]
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ MFISurveysProcessedDataGet } \emph{ Get a MFI processed data in long format; levels indicate the data aggregation level 1) Normalized Score, 2) Trader Aggregate Score, 3) Market Aggregate Score, 4) Trader Median, 5) Trader Mean, 6) Market Mean; each line corresponds to one of the nine dimensions of scores plus the final MFI aggregate score; 1) Assortment, 2) Availability, 3) Price, 4) Resilience, 5) Competition, 6) Infrastructure, 7) Service, 8) Quality, 9) Access and Protection, and 10) MFI final score; the variable label describes each variable and its value range }
#' [![Generic badge](https://img.shields.io/badge/Maturity\%20Level-Production\%20Ready-green)]()  [![Generic badge](https://img.shields.io/badge/Access\%20Policy-Open-green)]()  [![Generic badge](https://img.shields.io/badge/Data\%20Classification-Public-green)]()      **Data Controller** - Wael Attia  **API Integration Pattern** - This endpoint uses [Hey Jude](https://docs.api.wfp.org/providers/#api-patterns) pattern
#'
#' \itemize{
#' \item \emph{ @param } survey_id integer
#' \item \emph{ @param } page integer
#' \item \emph{ @param } format character
#' \item \emph{ @param } start_date character
#' \item \emph{ @param } end_date character
#' \item \emph{ @param } adm0_codes character
#' \item \emph{ @param } market_id integer
#' \item \emph{ @param } survey_type character
#' \item \emph{ @param } env Enum < [prod, dev] >
#' \item \emph{ @returnType } \link{PagedProcessedDataDTO} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PagedProcessedDataDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad Request
#'
#' \item return type : BadRequestDTO
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  MFISurveysBaseDataGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_survey_id <- 56 # integer | unique identifier for the collected data, as retrieved from /Surveys API. (Optional)
#' var_page <- 1 # integer | page number for paged results (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Get data that includes the core Market Functionality Index (MFI) fields only by Survey ID
#' api_instance <- SurveysApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$MFISurveysBaseDataGet(survey_id = var_survey_id, page = var_page, env = var_envdata_file = "result.txt")
#' result <- api_instance$MFISurveysBaseDataGet(survey_id = var_survey_id, page = var_page, env = var_env)
#' dput(result)
#'
#'
#' ####################  MFISurveysFullDataGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_survey_id <- 56 # integer | unique identifier for the collected data, as retrieved from /Surveys API. (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_page <- 1 # integer | page number for paged results (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Get a full dataset that includes all the fields included in the survey in addition to the core Market Functionality Index (MFI) fields by Survey ID. To access this data, please contact global.mfi@wfp.org for authorization.
#' api_instance <- SurveysApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$MFISurveysFullDataGet(survey_id = var_survey_id, format = var_format, page = var_page, env = var_envdata_file = "result.txt")
#' result <- api_instance$MFISurveysFullDataGet(survey_id = var_survey_id, format = var_format, page = var_page, env = var_env)
#' dput(result)
#'
#'
#' ####################  MFISurveysGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_adm0_code <- 0 # integer | code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion (Optional)
#' var_page <- 1 # integer | page number for paged results (Optional)
#' var_start_date <- "start_date_example" # character | starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24) (Optional)
#' var_end_date <- "end_date_example" # character | ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24) (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all MFI surveys conducted in a country. A date of reference, SurveyDate, for the data collection is set by the officer responsible of the upload for each survey.
#' api_instance <- SurveysApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$MFISurveysGet(adm0_code = var_adm0_code, page = var_page, start_date = var_start_date, end_date = var_end_date, env = var_envdata_file = "result.txt")
#' result <- api_instance$MFISurveysGet(adm0_code = var_adm0_code, page = var_page, start_date = var_start_date, end_date = var_end_date, env = var_env)
#' dput(result)
#'
#'
#' ####################  MFISurveysProcessedDataGet  ####################
#'
#' library(DataBridgesAPIr)
#' var_survey_id <- 56 # integer | The ID of the survey (Optional)
#' var_page <- 1 # integer | page number for paged results (Optional)
#' var_format <- "json" # character | Output format: [JSON|CSV] Json is the default value (Optional)
#' var_start_date <- "start_date_example" # character | Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24) (Optional)
#' var_end_date <- "end_date_example" # character | Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24) (Optional)
#' var_adm0_codes <- "adm0_codes_example" # character | Code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion (Optional)
#' var_market_id <- 56 # integer | The ID of the market (Optional)
#' var_survey_type <- "survey_type_example" # character | The survey type (Optional)
#' var_env <- "env_example" # character | Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org (Optional)
#'
#' #Get a MFI processed data in long format; levels indicate the data aggregation level 1) Normalized Score, 2) Trader Aggregate Score, 3) Market Aggregate Score, 4) Trader Median, 5) Trader Mean, 6) Market Mean; each line corresponds to one of the nine dimensions of scores plus the final MFI aggregate score; 1) Assortment, 2) Availability, 3) Price, 4) Resilience, 5) Competition, 6) Infrastructure, 7) Service, 8) Quality, 9) Access and Protection, and 10) MFI final score; the variable label describes each variable and its value range
#' api_instance <- SurveysApi$new()
#'
#' # Configure OAuth2 access token for authorization: default
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$MFISurveysProcessedDataGet(survey_id = var_survey_id, page = var_page, format = var_format, start_date = var_start_date, end_date = var_end_date, adm0_codes = var_adm0_codes, market_id = var_market_id, survey_type = var_survey_type, env = var_envdata_file = "result.txt")
#' result <- api_instance$MFISurveysProcessedDataGet(survey_id = var_survey_id, page = var_page, format = var_format, start_date = var_start_date, end_date = var_end_date, adm0_codes = var_adm0_codes, market_id = var_market_id, survey_type = var_survey_type, env = var_env)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
SurveysApi <- R6::R6Class(
  "SurveysApi",
  public = list(
    api_client = NULL,
    #' Initialize a new SurveysApi.
    #'
    #' @description
    #' Initialize a new SurveysApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Get data that includes the core Market Functionality Index (MFI) fields only by Survey ID
    #'
    #' @description
    #' Get data that includes the core Market Functionality Index (MFI) fields only by Survey ID
    #'
    #' @param survey_id (optional) unique identifier for the collected data, as retrieved from /Surveys API.
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return SurveyDetailsDTO
    #' @export
    MFISurveysBaseDataGet = function(survey_id = NULL, page = 1, env = NULL, data_file = NULL, ...) {
      local_var_response <- self$MFISurveysBaseDataGetWithHttpInfo(survey_id, page, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get data that includes the core Market Functionality Index (MFI) fields only by Survey ID
    #'
    #' @description
    #' Get data that includes the core Market Functionality Index (MFI) fields only by Survey ID
    #'
    #' @param survey_id (optional) unique identifier for the collected data, as retrieved from /Surveys API.
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (SurveyDetailsDTO) with additional information such as HTTP status code, headers
    #' @export
    MFISurveysBaseDataGetWithHttpInfo = function(survey_id = NULL, page = 1, env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE




      query_params[["surveyID"]] <- `survey_id`

      query_params[["page"]] <- `page`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling SurveysApi$MFISurveysBaseDataGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/MFI/Surveys/BaseData"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "SurveyDetailsDTO", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get a full dataset that includes all the fields included in the survey in addition to the core Market Functionality Index (MFI) fields by Survey ID. To access this data, please contact global.mfi@wfp.org for authorization.
    #'
    #' @description
    #' Get a full dataset that includes all the fields included in the survey in addition to the core Market Functionality Index (MFI) fields by Survey ID. To access this data, please contact global.mfi@wfp.org for authorization.
    #'
    #' @param survey_id (optional) unique identifier for the collected data, as retrieved from /Surveys API.
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return SurveyDetailsDTO
    #' @export
    MFISurveysFullDataGet = function(survey_id = NULL, format = "json", page = 1, env = NULL, data_file = NULL, ...) {
      local_var_response <- self$MFISurveysFullDataGetWithHttpInfo(survey_id, format, page, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get a full dataset that includes all the fields included in the survey in addition to the core Market Functionality Index (MFI) fields by Survey ID. To access this data, please contact global.mfi@wfp.org for authorization.
    #'
    #' @description
    #' Get a full dataset that includes all the fields included in the survey in addition to the core Market Functionality Index (MFI) fields by Survey ID. To access this data, please contact global.mfi@wfp.org for authorization.
    #'
    #' @param survey_id (optional) unique identifier for the collected data, as retrieved from /Surveys API.
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (SurveyDetailsDTO) with additional information such as HTTP status code, headers
    #' @export
    MFISurveysFullDataGetWithHttpInfo = function(survey_id = NULL, format = "json", page = 1, env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE





      query_params[["surveyID"]] <- `survey_id`

      query_params[["format"]] <- `format`

      query_params[["page"]] <- `page`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling SurveysApi$MFISurveysFullDataGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/MFI/Surveys/FullData"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- "vamdatabridges_mfi-surveys-fulldata_get"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "SurveyDetailsDTO", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all MFI surveys conducted in a country. A date of reference, SurveyDate, for the data collection is set by the officer responsible of the upload for each survey.
    #'
    #' @description
    #' Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all MFI surveys conducted in a country. A date of reference, SurveyDate, for the data collection is set by the officer responsible of the upload for each survey.
    #'
    #' @param adm0_code (optional) code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion (default value: 0)
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param start_date (optional) starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24)
    #' @param end_date (optional) ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return array[PagedSurveyListDTO]
    #' @export
    MFISurveysGet = function(adm0_code = 0, page = 1, start_date = NULL, end_date = NULL, env = NULL, data_file = NULL, ...) {
      local_var_response <- self$MFISurveysGetWithHttpInfo(adm0_code, page, start_date, end_date, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all MFI surveys conducted in a country. A date of reference, SurveyDate, for the data collection is set by the officer responsible of the upload for each survey.
    #'
    #' @description
    #' Retrieve 1) Survey IDs, 2) their corresponding XLS Form IDs, and 3) Base XLS Form of all MFI surveys conducted in a country. A date of reference, SurveyDate, for the data collection is set by the officer responsible of the upload for each survey.
    #'
    #' @param adm0_code (optional) code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion (default value: 0)
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param start_date (optional) starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24)
    #' @param end_date (optional) ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24)
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (array[PagedSurveyListDTO]) with additional information such as HTTP status code, headers
    #' @export
    MFISurveysGetWithHttpInfo = function(adm0_code = 0, page = 1, start_date = NULL, end_date = NULL, env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE






      query_params[["adm0Code"]] <- `adm0_code`

      query_params[["page"]] <- `page`

      query_params[["startDate"]] <- `start_date`

      query_params[["endDate"]] <- `end_date`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling SurveysApi$MFISurveysGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/MFI/Surveys"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "array[PagedSurveyListDTO]", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get a MFI processed data in long format; levels indicate the data aggregation level 1) Normalized Score, 2) Trader Aggregate Score, 3) Market Aggregate Score, 4) Trader Median, 5) Trader Mean, 6) Market Mean; each line corresponds to one of the nine dimensions of scores plus the final MFI aggregate score; 1) Assortment, 2) Availability, 3) Price, 4) Resilience, 5) Competition, 6) Infrastructure, 7) Service, 8) Quality, 9) Access and Protection, and 10) MFI final score; the variable label describes each variable and its value range
    #'
    #' @description
    #' Get a MFI processed data in long format; levels indicate the data aggregation level 1) Normalized Score, 2) Trader Aggregate Score, 3) Market Aggregate Score, 4) Trader Median, 5) Trader Mean, 6) Market Mean; each line corresponds to one of the nine dimensions of scores plus the final MFI aggregate score; 1) Assortment, 2) Availability, 3) Price, 4) Resilience, 5) Competition, 6) Infrastructure, 7) Service, 8) Quality, 9) Access and Protection, and 10) MFI final score; the variable label describes each variable and its value range
    #'
    #' @param survey_id (optional) The ID of the survey
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24)
    #' @param adm0_codes (optional) Code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion
    #' @param market_id (optional) The ID of the market
    #' @param survey_type (optional) The survey type
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return PagedProcessedDataDTO
    #' @export
    MFISurveysProcessedDataGet = function(survey_id = NULL, page = 1, format = "json", start_date = NULL, end_date = NULL, adm0_codes = NULL, market_id = NULL, survey_type = NULL, env = NULL, data_file = NULL, ...) {
      local_var_response <- self$MFISurveysProcessedDataGetWithHttpInfo(survey_id, page, format, start_date, end_date, adm0_codes, market_id, survey_type, env, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get a MFI processed data in long format; levels indicate the data aggregation level 1) Normalized Score, 2) Trader Aggregate Score, 3) Market Aggregate Score, 4) Trader Median, 5) Trader Mean, 6) Market Mean; each line corresponds to one of the nine dimensions of scores plus the final MFI aggregate score; 1) Assortment, 2) Availability, 3) Price, 4) Resilience, 5) Competition, 6) Infrastructure, 7) Service, 8) Quality, 9) Access and Protection, and 10) MFI final score; the variable label describes each variable and its value range
    #'
    #' @description
    #' Get a MFI processed data in long format; levels indicate the data aggregation level 1) Normalized Score, 2) Trader Aggregate Score, 3) Market Aggregate Score, 4) Trader Median, 5) Trader Mean, 6) Market Mean; each line corresponds to one of the nine dimensions of scores plus the final MFI aggregate score; 1) Assortment, 2) Availability, 3) Price, 4) Resilience, 5) Competition, 6) Infrastructure, 7) Service, 8) Quality, 9) Access and Protection, and 10) MFI final score; the variable label describes each variable and its value range
    #'
    #' @param survey_id (optional) The ID of the survey
    #' @param page (optional) page number for paged results (default value: 1)
    #' @param format (optional) Output format: [JSON|CSV] Json is the default value (default value: "json")
    #' @param start_date (optional) Starting date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24)
    #' @param end_date (optional) Ending date for the range in which data was collected. Use the date formats defined by RFC 3339 ; use strings matching year \"-\" month \"-\" day (e.g. 2020/06/24)
    #' @param adm0_codes (optional) Code for the country as retrieved from https://api.vam.wfp.org/geodata/CountriesInRegion
    #' @param market_id (optional) The ID of the market
    #' @param survey_type (optional) The survey type
    #' @param env (optional) Environment.   * `prod` - api.vam.wfp.org   * `dev` - dev.api.vam.wfp.org
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (PagedProcessedDataDTO) with additional information such as HTTP status code, headers
    #' @export
    MFISurveysProcessedDataGetWithHttpInfo = function(survey_id = NULL, page = 1, format = "json", start_date = NULL, end_date = NULL, adm0_codes = NULL, market_id = NULL, survey_type = NULL, env = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE










      query_params[["surveyID"]] <- `survey_id`

      query_params[["page"]] <- `page`

      query_params[["format"]] <- `format`

      query_params[["startDate"]] <- `start_date`

      query_params[["endDate"]] <- `end_date`

      query_params[["adm0Codes"]] <- `adm0_codes`

      query_params[["marketID"]] <- `market_id`

      query_params[["surveyType"]] <- `survey_type`

      if (!(`env` %in% c("prod", "dev"))) {
        stop("Invalid value for env when calling SurveysApi$MFISurveysProcessedDataGet. Must be [prod, dev].")
      }
      query_params[["env"]] <- `env`

      local_var_url_path <- "/MFI/Surveys/ProcessedData"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "text/json", "text/plain")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "PagedProcessedDataDTO", loadNamespace("DataBridgesAPIr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
